# RAG 평가 개요
- RAG 평가란 RAG 시스템이 주어진 입력에 대해 얼마나 효과적으로 관련 정보를 검색하고, 이를 기반으로 정확하고 유의미한 응답을 생성하는지를 측정하는 과정이다. 
- **평가 요소**
    - **검색 단계 평가**
        - 입력 질문에 대해 검색된 문서나 정보의 관련성과 정확성을 평가.
    - **생성 단계 평가**
        - 검색된 정보를 기반으로 생성된 응답의 품질, 정확성등을 평가.
- **평가 방법**
    - **온/오프라인 평가**
        1. **오프라인 평가**
            - 미리 준비된 데이터셋을 활용하여 RAG 시스템의 성능을 측정한다.
        2. **온라인 평가**
            - 실제 사용자 트래픽과 피드백을 기반으로 시스템의 실시간 성능을 평가한다.
    - **정량적/정성적 평가**
        1. 정량적 평가
            - 자동화된 지표를 사용하여 생성된 텍스트의 품질을 평가한다.
        2. 정성적 평가
            - 전문가나 일반 사용자가 직접 생성된 응답의 품질을 평가하여 주관적인 지표를 평가한다.

# [RAGAS](https://www.ragas.io/)
- RAGAS는 RAG 파이프라인을 **정량적으로 평가하는** 오픈소스 프레임 워크이다. 
- RAGAS 문서: https://docs.ragas.io/en/stable/
## 설치
- `pip install ragas rapidfuzz`

## RAGAS 평가 지표 개요
![ragas_score](figures/ragas_score.png)
- **Generation**
    - llm 모델이 생성한 답변에 대한 평가 지표들.
    - **Faithfulness(신뢰성)**
        -  생성된 답변과 검색된 문서(context)간의 관련성을 평가하는 지표
        -  생성된 답변이 주어진 문맥(context)에 얼마나 충실한지를 평가하는 지표로 할루시네이션에 대한 평가로 볼 수있다.
    - **Answer relevancy(답변 적합성)**
        - 생성된 답변과 사용자의 질문간의 관련성을 평가하는 지표
        - 생성된 답변이 사용자의 질문과 얼마나 관련성이 있는지를 평가하는 지표.
- **Retrieval**
    -  질문에 대해 검색한 문서(context)들에 대한 평가
    -  **Context Precision(문맥 정밀도)**
        -  검색된 문서(context)들 중 질문과 관련 있는 것들이 **얼마나 상위 순위에 위치하는지** 평가하는 지표.
    -  **Context Recall(문맥 재현률)**
        -  검색된 문서(context)가 정답(ground-truth)의 정보를 얼마나 포함하고 있는지 평가하는 지표.
- 이러한 지표들은 RAG 파이프라인의 성능을 다각도로 평가하는 데 활용된다.
![RAGAS_score2](figures/RAGAS_score2.png)

## 주요 평가지표
### Generation 평가
- LLM이 생성한 답변에 대한 평가
  
#### Faithfulness (신뢰성)
- 생성된 답변이 얼마나 주어진 검색 문서들(context)를 잘 반영해서 생성되었는지 평가한다. 할루시네이션에 대한 평가라고 할 수 있다. 
- 점수범위: **0 ~ 1** (1에 가까울수록 좋음)
- 답변에 포함된 모든 주장이 context에서 얼마나 추출 가능한지를 확인한다.

##### 평가 방법
1. Answer에서 주장 구문(claim statement)들을 생성(추출)한다. (주장이란, 질문(user input)과 관련된 내용)
    - 예) 
        - **질문**: 한국의 수도는 어디이고 인구는 얼마나 되나요? 
        - **LLM 답변**: 한국의 수도는 서울이고 인구수는 3000만명이다. 
        - **주장(claim)**: 
            1. 한국의 수도는 서울이다.
            2. 인구수는 3000만명이다.
2. 각 주장들을 context로 부터 추론 가능한지 판단한다. 이를 바탕으로 faithfulness 점수를 계산한다.
    - 예)
        - context: 한국은 동아시아에 위치하고 있는 나라다. 한국의 수도는 서울이다. .... 한국의 인구는 5000만명이고 서울에 1000만이 살고 있다.
        - 위 context에서 추론 가능한 주장: 
            - 한국의 수도는 서울이다. -> context에서 추론가능한 주장.
            - 한국의 인구는 3000만명이다. -> context에서 추론 불가능한 주장.
3. **Faithfulness score** 를 계산한다. 총 주장 수 중에서 context로 부터 추론가능한 주장의 개수.    
    - 예)
        - Faithfulness Score = $\cfrac{1}{2} = 0.5$ (두 개의 주장 중 한 개의 주장만 context에서 유추할 수있다.)
    - LLM 답변에서 주장을 추출 하는 것과 각 주장이 context에서 추론 가능한 지를 판단하는 것은 LLM 을 활용한다.
- 공식
    $$
    \text{Faithfulness Score}\;=\;\cfrac{\text{주어진\;context\;에서\;추론할\;수\;있는\;주장의\;개수}}{\text{총\;주장\;개수}}
    $$

### Answer relevancy (답변 적합성)
- 생성된 답변이 질문(user input)에 얼마나 잘 부합하는 지를 평가한다.
- 점수 범위: -1~1 (1에 가까울수록 좋음)
- LLM이 생성한 답변을 기반으로 질문들을 생성한다. 이렇게 생성한 질문들과 실제 질문(user input) 간의 유사도를 측정한다.

#### 평가방법
1. LLM이 생성한 답변을 기반으로 질문들을 생성한다.
    - 예) 
        - **LLM** 답변: 한국의 수도는 서울이고 인구수는 3000만명이다. 
        - **생성된 질문**: 
            1. 한국의 수도는 어디이고 인구는 얼마나 되나요?
            2. 한국의 수도는 어디인가요?
            3. 한국의 인구는 얼마나 되나요?
2. 실제 질문과 생성한 질문간의 코사인 유사도를 측정한다. 그 평균이 최종 점수가 된다.
    - 예)
        - **실제 질문**: 한국의 수도는 어디이고 인구는 얼마나 되나요?
        - **생성된 질문**: 
            1. 한국의 수도는 어디이고 인구는 얼마나 되나요?
            2. 한국의 수도는 어디인가요?
            3. 한국의 인구는 얼마나 되나요?
- 공식
  $$
    \cfrac{1}{N} \sum_{i=1}^{N} \text{cosine\_similarity}(q_{\text{user}_{_i}}, q_{\text{generated}})
  $$

## Retrieval 평가
Vector store에서 검색한 context에 대한 평가

### Context Precision
- 검색된 문서(context)들 중 질문과 관련 있는 것들이 얼마나 **상위 순위**에 있는 지 평가.
- 점수 범위: 0~1 (1에 가까울수록 좋음)


#### 평가방법

- 공식
$$
 \text{Context\;Precision@K} = \frac{\sum_{k=1}^{K} \left( \text{Precision@k} \times v_k \right)}{\ 상위\;K개\;결과에서의\;관련\;항목\;수}
$$
$$
 \text{Precision@k} = \frac{\text{True\;positive@k}}{(\text{True\;positive@k} + \text{False\;positive@k})} \\
$$
- $\text{Precision@k}$: 개별 문서에 대한 Precision
- K: context 의 개수(chuck 수)
- $v_k$: 관련성 여부로 0 또는 1. (0: 관련 없음, 1: 관련 있음)

#### 예시
- 질문과 context 관련성의 예
    - 질문: 한국의 수도는 어디이고 인구는 얼마나 되나요?
    - **높은 정밀도 context들**: 질문과 직접적인 관련이 있는 문서들
        - 한국의 수도는 서울이고 인구는 5000만명 입니다. 
        - 한국의 수도는 서울입니다.
        - 한국은 동아시아에 위치해 있는 국가로 수도는 서울입니다.
        - 한국의 인구는 5000만명 입니다.
    - **낮은 정밀도 context**: 한국과 관련있어 검색될 수 있지만 질문과 직접적 관련이 없다. 
        - 한국은 동아시아에 위치한 국가입니다.
        - 한국의 K-pop은 전 세계적으로 유명합니다.
        - 비빔밥, 불고기는 한국의 대표적인 음식입니다.
    - **높은 정밀도의 context이 상위 순위에 위치했으면 높은 점수를 받는다.**

- 점수 계산 예:
    - **상위 5개의 검색 결과 중 1번째, 3번째, 4번째 문서가 관련이 있다고 가정하자.**
    - **Precision@K 계산**
        ```bash
            Precision@1 = 1/1 = 1.0    # True positive@1/(True positive@1 + False positive@1).  1/1(1번 문서 계산 시에는 1개 문서만 있으므로 분모가 1이 된다.)
            Precision@2 = 1/2 = 0.5
            Precision@3 = 2/3 ≈ 0.67    
            Precision@4 = 3/4 = 0.75
            Precision@5 = 3/5 = 0.6
        ```
    - **vk의 값**
        - 1번째: $v_1 = 1$ - 관련있음
        - 2번째: $v_2 = 0$ - 관련없음
        - 3번째: $v_3 = 1$ - 관련있음
        - 4번째: $v_4 = 1$ - 관련있음
        - 5번째: $v_5 = 0$ - 관련없음

    - **Context Precision@5**
        $$
        \text{Context\;Precision@5} = \frac{(1.0 \times 1) + (0.5 \times 0) + (0.67 \times 1) + (0.75 \times 1) + (0.6 \times 0)}{3} = \frac{1.0 + 0 + 0.67 + 0.75 + 0}{3} ≈ 0.807
        $$

### Context Recall (문맥 재현률)
- 검색된 문서(context)가 얼마나 정답(ground-truth)의 정보를 포함있는 지 평가하는 지표
- 점수 범위: 0~1 (1에 가까울수록 좋음)
- **정답(ground truth)의 각 주장(claim)이 검색된 context와 얼마나 일치**하는지 계산함.

#### 평가방법
1. 정답에서 주장(claim)들을 생성(추출)한다.
    - 예) 
        - **정답**: 한국의 수도는 서울이고 인구수는 5000만명이다. 
        - **주장(claim)**: 
            1. 한국의 수도는 서울이다.
            2. 인구수는 5000만명이다.
2. 각 주장(claim)의 정보를 검색된 contexts에서 찾을 수 있는지 판별한다. 이를 바탕으로 context recall 점수를 계산한다.
    - 예)
        - context: 한국은 동아시아에 위치하고 있는 나라다. 한국의 수도는 서울이다.
        - 위 context에서 추론 가능한 주장: 
            - 한국의 수도는 서울이다. -> context에서 찾을 수 있다.
            - 한국의 인구는 5000만명이다. -> context에서 찾을 수 없다.
3. **Context Recall Score** 를 계산한다. 총 주장 수 중에서 context로 부터 찾을 수 있는 주장의 개수.
    - 예)
        - Context Recall Score = $\cfrac{1}{2} = 0.5$ (두 개의 주장 중 한 개의 주장만 context에서 찾을 수 있다.)

- 공식
    $$
    \text{Context Recall Score}\;=\;\cfrac{\text{GT의\;주장\;중\;주어진\;context\;에서\;찾을\;수\;있는\;주장의\;개수}}{\text{GT의\;총\;주장\;개수}}
    $$

# RAGAS 평가 실습

In [ ]:
# !uv pip install ragas rapidfuzz
# 설치 후 커널 재시작

In [ ]:
# docker run -p 6333:6333 -p 6334:6334   -v qdrant_storage:/qdrant/storage   qdrant/qdrant

In [4]:
from langchain_text_splitters import MarkdownHeaderTextSplitter
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

from langchain_openai import ChatOpenAI
from langchain_qdrant import FastEmbedSparse, QdrantVectorStore, RetrievalMode
from qdrant_client import QdrantClient, models
from qdrant_client.models import Distance, SparseVectorParams, VectorParams
from langchain_openai import OpenAIEmbeddings

from dotenv import load_dotenv

load_dotenv()

True

In [27]:
# ##############################################################
# 데이터 준비
##############################################################

def load_and_split_olympic_data(file_path="data/olympic_wiki.md"):
    with open(file_path, "r", encoding="utf-8") as fr:
        olympic_text = fr.read()

    # Split
    splitter = MarkdownHeaderTextSplitter(
        headers_to_split_on=[
            ("#", "H1"),
            ("##", "H2"),
            ("###", "H3"),
        ],
    )

    return splitter.split_text(olympic_text)

In [28]:
#################################################################
# Vector DB 연결
# retriever 생성
#################################################################

def get_vectorstore(collection_name: str = "olympic_info_wiki"):


    dense_embeddings = OpenAIEmbeddings(model="text-embedding-3-large")

    client = QdrantClient(url="http://localhost:6333")

    # 컬렉션 삭제
    if client.collection_exists(collection_name):
        result = client.delete_collection(collection_name=collection_name)

    # 컬렉션 생성
    client.create_collection(
        collection_name=collection_name,
        vectors_config=VectorParams(size=3072, distance=Distance.COSINE),
      
    )

    vectorstore = QdrantVectorStore(
        client=client,
        collection_name=collection_name,    
        embedding=dense_embeddings
    )
    
    ######################################
    # Document들 추가
    ######################################
    documents = load_and_split_olympic_data()
    vectorstore.add_documents(documents=documents)

    return vectorstore


def get_retriever(vectorstore, k: int = 5):
    retriever = vectorstore.as_retriever(
        search_kwargs={"k": k}
    )
    return retriever

In [29]:
vectorstore = get_vectorstore()

retriever = get_retriever(vectorstore)
retriever

VectorStoreRetriever(tags=['QdrantVectorStore', 'OpenAIEmbeddings'], vectorstore=<langchain_qdrant.qdrant.QdrantVectorStore object at 0x000001F3AEEA6E40>, search_kwargs={'k': 5})

In [30]:
################################################################################
# 평가할 RAG Chain
################################################################################

from langchain_core.prompts import PromptTemplate, ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough 
from langchain_core.output_parsers import StrOutputParser
from langchain_core.documents import Document
from operator import itemgetter

vectorstore = get_vectorstore()
retriever = get_retriever(vectorstore)

prompt_txt = """<instruction>
당신은 정보제공을 목적으로하는 유능한 AI Assistant 입니다.
주어진 context의 내용을 기반으로 질문에 답변을 합니다.
Context에 질문에 대한 명확한 정보가 있는 경우 그것을 바탕으로 답변을 합니다.
Context에 질문에 대한 명확한 정보가 없는 경우 "정보가 부족해 답을 할 수없습니다." 라고 답합니다.
절대 추측이나 일반 상식을 바탕으로 답을 하거나 Context 없는 내용을 만들어서 답변해서는 안됩니다.
</instruction>
<context>
{context}
</context>
<question>
{query}
</question>
"""
prompt = ChatPromptTemplate.from_template(
    template=prompt_txt
)

model = ChatOpenAI(model="gpt-5.4-mini")
parser = StrOutputParser()

def format_doc_to_str(documents:list[Document])->list[str]:
    """
    VectorStore에 조회한 문서들(list[Document])에서 내용(page_content)만 추출해서 list[str] 로 반환.
    RAGAS 평가시 context는 각 검색한 문서를 list[str] 로 받기 때문에 이렇게 처리.
    
    Args:
        documents(list[Document]): [Document(..), Document(...), ..]}
    Returns:
        list[str]: 각 문서의 내용만 추출해서 리스트에 담는다.
    """
    return [doc.page_content for doc in documents]

# RAG 체인 -> 평가데이터셋을 만드는 RAG Chain
#          -> 최종 응답: LLM의 응답(str), 검색한 문서들(list[str])
chain = RunnablePassthrough() | {
    "context":retriever | format_doc_to_str,
    "query":RunnablePassthrough()
} | { 
    "response": prompt | model | parser,
    "retrieved_context": itemgetter("context")
}
# RunnablePassthrough() -> LCEL 체인을 만들려면 구성요소중 하나가 Runnable이어야 하는데
# 이 체인은 dict | dict 구조기 때문에 앞에 추가.

In [6]:
res = chain.invoke("1회 올림픽은 언제 어디서 열렸지")

In [7]:
print(res.keys())

dict_keys(['response', 'retrieved_context'])

In [8]:
res['response']

'기원전 776년에 그리스 올림피아에서 열렸습니다.'

In [9]:
res['retrieved_context']

['고대의 올림픽 경기(올림피아 경기)는 고대 그리스의 여러 도시 국가의 대표선수들이 모여 벌인 일련의 시합이었으며, 육상 경기가 주 종목이지만 격투기와 전차 경기도 열렸다. 그리고 패배하면 죽기도 하였다. 고대 올림픽의 유래는 수수께끼로 남아있다. 잘 알려진 신화로는 헤라클레스와 그의 아버지인 제우스가 올림픽의 창시자였다는 것이다. 전설에 따르면 이 경기를 최초로 \'올림픽\'이라고 부르고, 4년마다 대회를 개최하는 관례를 만든 사람이 헤라클레스라고 한다. 어떤 전설에서는 헤라클레스가 이른바 헤라클레스의 12업을 달성한 뒤에 제우스를 기리고자 올림픽 경기장을 지었다고 한다. 경기장이 완성되자 헤라클레스는 일직선으로 200 걸음을 걸었으며, 이 거리를 "스타디온"이라 불렀는데, 후에 이것이 길이 단위인 \'스타디온\'(그리스어: στάδιον → 라틴어: 영어: stadium)이 되었다. 또 다른 설로는 \'올림픽 휴전\'(그리스어: ἐκεχειρία 에케케이리아[*])이라는 고대 그리스의 관념이 최초의 올림피아 경기와 관련이 있다고 한다. \'올림픽 휴전\'이란 어느 도시 국가라도 올림피아 경기 기간 중에 다른 나라를 침범하면 그에 대한 응징을 받을 수 있다는 뜻으로, "올림픽 기간에는 전쟁하지 말 것"으로 요약할 수 있다.  \n고대 올림피아 경기가 처음 열린 시점은 보통 기원전 776년으로 인정되고 있는데, 이 연대는 그리스 올림피아에서 발견된 비문에 근거를 둔 것이다. 이 비문의 내용은 달리기 경주 승자 목록이며 기원전 776년부터 4년 이후 올림피아 경기 마다의 기록이 남겨져 있다. 고대 올림픽의 종목으로는 육상, 5종 경기(원반던지기, 창던지기, 달리기, 레슬링, 멀리뛰기), 복싱, 레슬링, 승마 경기가 있었다. 전설에 따르면 엘리스의 코로이보스가 최초로 올림피아 경기에서 우승한 사람이라고 한다.  \n고대 올림피아 경기는 근본적으로 종교적인 중요성을 띄고 있었는데, 스포츠 경기를 할 때는 제우스(올림피아의 제우스 신전에는 페이디아스가 만든 제우스 상이 있음)와 펠롭스를 기리기 위하여 제물 봉헌 의식을 치렀다. 펠롭스는 올림피아의 전설상의 임금이었던 피사티스의 오이노마오스 왕과 전차 경주를 겨룬 영웅으로 유명한 인물이다. 올림피아 경기의 승자는 시와 조각상으로 칭송받았다. 올림피아 경기는 4년마다 열렸으며, 이 기간을 \'올림피아드\'(Olympiad)라고 했는데, 그리스인들은 이를 시간 단위로 이용하였다. 올림피아 경기는 고대 그리스에서 정기적으로 열렸던 범그리스 대회의 순환 대회 가운데 하나였다.  \n올림피아 경기는 기원전 6세기~기원전 5세기에 절정에 이르렀으나, 그 후 로마가 패권을 잡은 뒤 그리스에 영향력을 행사하면서 서서히 쇠퇴하게 된다. 고대 올림픽이 공식적으로 끝난 해는 확실히 알 수 없으나, 대부분 테오도시우스 1세 황제가 모든 이단 숭배 및 예배를 금지했던 393년을 고대 올림픽의 마지막이라고 추정한다. 다른 설에 따르면 테오도시우스의 후계자인 테오도시우스 2세가 모든 그리스 신전을 파괴하라고 명령한 426년이라고도 한다. 이렇게 올림픽이 사라진 이후로 이보다 한참 뒤인 19세기에 이르러서야 비로소 다시 올림픽 경기가 열리게 된다.',
 '쿠베르탱의 생각과는 달리, 올림픽이 세계에 완벽한 평화를 가져다주지는 못했다. 실제로 제1차 세계대전으로 인해 독일 베를린에서 열리기로 했던 제6회 1916년 하계 올림픽이 취소되었고, 제2차 세계대전 때는 일본 도쿄에서 열리기로 했던 제12회 1940년 하계 올림픽, 삿포로에서 열리기로 했던 1940년 동계 올림픽, 영국 런던에서 열리기로 했던 제13회 1944년 하계 올림픽, 이탈리아 코르티나담페초에서 열릴 예정인 1944년 동계 올림픽이 취소되었다. 베이징에서 열린 2008년 하계 올림픽 개막식날 조지아와 러시아 간의 2008년 남오세티아 전쟁이 일어나기도 했다. 부시 대통령과 푸틴 대통령이 이 올림픽을 보러 왔으며 중국 주석인 후진타오가 주최한 오찬에 참석해서 이 현안에 대해 논의하기도 했다. 조지아 대표인 니노 살루크바체와 러시아 대표인 나탈리야 파데리나가 여자 10m 공기권총 경기에서 각각 동메달과 은메달을 땄을 때 이 일은 베이징 올림픽의 유명한 사건 중 하나로 남게 되었다. 살루크바체와 파데리나는 시상식이 끝난 뒤 서로 포옹을 하며 국적에 상관없이 기쁨을 나누었다.  \n테러도 올림픽에서 공포의 대상이었다. 뮌헨 참사로 알려진 1972년에 서독 바이에른의 뮌헨에서 열린 하계 올림픽때의 사건은 테러리스트인 검은 9월단이 일으킨 사건으로서 이스라엘 선수 11명을 인질로 붙잡았다가 전원이 사망한 사건이다. 당시 미숙한 진압으로 인해 인질 9명(선수 1명과 코치 1명은 인질로 잡기 이전에 살해), 테러범 5명, 독일 경찰관 1명이 사망했으며 이 진압 작전 이전에는 인질들은 단 한 명도 죽지 않았다. 애틀랜타에서 열린 1996년 하계 올림픽 때는 센테니얼 올림픽 공원(Centennial Olympic Park)에서 폭발 사건이 일어나 2명이 죽고 111명이 다치는 사건이 발생했다. 이 사건의 주모자 에릭 로버트 루돌프는 종신형을 선고받았다. 참고로 마라톤 역시 전쟁에서 유래한 것이다.',
 '올림픽(영어: Olympic Games, 프랑스어: Jeux olympiques)은 전 세계 각 대륙 각국에서 모인 수천 명의 선수가 참가해 여름과 겨울에 스포츠 경기를 하는 국제적인 대회이다. 전 세계에서 가장 큰 지구촌 최대의 스포츠 축제인 올림픽은 세계에서 가장 인지도있는 국제 행사이다. 올림픽은 2년마다 하계 올림픽과 동계 올림픽이 번갈아 열리며, 국제 올림픽 위원회(IOC)가 감독하고 있다. 또한 오늘날의 올림픽은 기원전 8세기부터 서기 5세기에 이르기까지 고대 그리스 올림피아에서 열렸던 올림피아 제전에서 비롯되었다. 그리고 19세기 말에 피에르 드 쿠베르탱 남작이 고대 올림피아 제전에서 영감을 얻어, 근대 올림픽을 부활시켰다. 이를 위해 쿠베르탱 남작은 1894년에 IOC를 창설했으며, 2년 뒤인 1896년에 그리스 아테네에서 제 1회 올림픽이 열렸다. 이때부터 IOC는 올림픽 운동의 감독 기구가 되었으며, 조직과 활동은 올림픽 헌장을 따른다. 오늘날 전 세계 대부분의 국가에서 올림픽 메달은 매우 큰 영예이며, 특히 올림픽 금메달리스트는 국가 영웅급의 대우를 받으며 스포츠 스타가 된다. 국가별로 올림픽 메달리스트들에게 지급하는 포상금도 크다. 대부분의 인기있는 종목들이나 일상에서 쉽게 접하고 즐길 수 있는 생활스포츠 종목들이 올림픽이라는 한 대회에서 동시에 열리고, 전 세계 대부분의 국가 출신의 선수들이 참여하는 만큼 전 세계 스포츠 팬들이 가장 많이 시청하는 이벤트이다. 2008 베이징 올림픽의 모든 종목 누적 시청자 수만 47억 명에 달하며, 이는 인류 역사상 가장 많은 수의 인구가 시청한 이벤트였다.  \n또한 20세기에 올림픽 운동이 발전함에 따라, IOC는 변화하는 세계의 사회 환경에 적응해야 했다. 이러한 변화의 예로는 얼음과 눈을 이용한 경기 종목을 다루는 동계 올림픽, 장애인이 참여하는 패럴림픽, 스페셜 올림픽, 데플림픽, 10대 선수들이 참여하는 유스 올림픽 등을 들 수 있다. 그 뿐만 아니라 IOC는 20세기의 변화하는 경제, 정치, 기술 환경에도 적응해야 했다. 그리하여 올림픽은 피에르 드 쿠베르탱이 기대했던 순수한 아마추어 정신에서 벗어나서, 프로 선수도 참가할 수 있게 되었다. 올림픽은 점차 대중 매체의 중요성이 커짐에 따라 올림픽의 상업화와 기업 후원을 놓고도 논란이 생겨났다. 또한 올림픽을 치르며 발생한 보이콧, 도핑, 심판 매수, 테러와 같은 수많은 일들은 올림픽이 더욱 굳건히 성장할 수 있는 원동력이 되었다.  \n올림픽은 국제경기연맹(IF), 국가 올림픽 위원회(NOC), 각 올림픽의 위원회(예-벤쿠버동계올림픽조직위원회)로 구성된다. 의사 결정 기구인 IOC는 올림픽 개최 도시를 선정하며, 각 올림픽 대회마다 열리는 올림픽 종목도 IOC에서 결정한다. 올림픽 경기 개최 도시는 경기 축하 의식이 올림픽 헌장에 부합하도록 조직하고 기금을 마련해야 한다. 올림픽 축하 행사로는 여러 의식과 상징을 들 수 있는데 올림픽기나 성화가 그 예이다.  \n올림픽은 거의 모든 국가가 참여할 정도로 규모가 커졌다. 하계 올림픽은 33개의 종목과 약 400개의 세부종목에서 13,000명이 넘는 선수들이 겨루고 그중 각 종목별 1, 2, 3위는 각각 금/은/동을 수여받는다. 전 세계 언론에서 각각 4년마다 열리는 올림픽 경기를 중계하기 때문에 이름 없는 선수가 개인적, 국가적, 세계적으로 명성을 얻을 수 있는 기회가 된다. 이와 더불어 올림픽 경기는 개최지와 개최국에게도 전 세계에 그 이름을 널리 알리는 좋은 기회가 된다.',
 '올림픽 개최지는 해당 올림픽 개최 7년 전에 IOC 위원들의 투표로 결정된다. 개최지 선정에는 약 2년이 걸린다. 유치를 희망하는 도시는 우선 자국의 올림픽 위원회에 신청을 해야 한다. 만약 한 국가에서 두 도시 이상이 유치를 희망한다면, 한 국가당 한 도시만 후보가 될 수 있다는 규칙에 따라 내부적으로 후보 도시를 결정해야 한다. 후보 도시가 결정되면 후보 도시가 소속된 국가의 올림픽 위원회는 IOC에 개최 신청을 하고, 신청 후에는 올림픽 개최에 대한 질의 응답서를 보내야 한다. 이 질의응답서에서 신청한 도시는 올림픽 헌장을 준수하며 IOC 상임이사회에 의한 다른 규정들을 지킬 것이라는 확신을 주어야 한다. 이 질의응답서는 전문가들이 검토하여 신청 도시들의 잠재성과 계획을 평가한다. 이 전문적인 평가를 바탕으로 IOC 상임이사회에서는 신청도시 중에서 후보도시를 고른다.  \n후보도시로 선택되면 그 도시들은 IOC에 보내는 후보도시에 관한 문서에 그들의 계획을 더욱 상세하고 방대한 양으로 적어서 보내야 한다. 평가조사단들이 이 후보도시들을 평가한다. 평가조사단은 후보도시들을 방문해서 지역 관계자들과 회견을 갖고 경기장 시설을 세심하게 조사한 뒤 개최지 투표를 하기 한달전에 조사를 바탕으로 한 공식 보고를 한다. 회견을 하는 동안에도 후보도시들은 자신들이 올림픽을 개최하는 데 충분한 자금이 조달될 수 있는지 등을 입증할 수 있어야 한다. 평가조사단의 업무가 끝나면 후보지의 국가 위원들은 IOC 정기총회에 참석한다. 이 총회에서 IOC 위원들은 올림픽 개최지를 선정하게 되며 후보지의 국가에 소속된 위원들은 자국의 후보지가 탈락하지 않는 이상 투표를 할 수 없다. 투표가 끝난후에 개최지로 선정된 곳의 유치위원회가 IOC와 개최도시 계약서에 서명을 하면 공식적으로 올림픽 개최도시(개최국)으로 인정된다.  \n2016년까지 올림픽은 23개국 44개 도시에서 열렸으며 유럽과 북아메리카대륙 이외의 대륙에서는 고작 8번 밖에 개최하지 못했다. 1988년 하계 올림픽이 대한민국의 서울에서 열린것을 시작으로 그 후 아시아와 오세아니아 대륙에서 올림픽이 4번이나 열렸으며, 이는 그 이전의 현대 올림픽사와 비교해보면 엄청나게 늘어난 수치였다. 2016년 하계 올림픽이 개최된 브라질의 리우데자네이루는 남미에서 열리는 첫 번째 올림픽이다. 아직 아프리카에서는 올림픽이 한 번도 개최되지 않았다. 2008년 하계 올림픽 때 가장 많은 선수가 참여한 나라는 중국으로 639명이 참가했으며 그 다음은 미국과 러시아로 각각 596명과 455명이 참가했다.  \n미국은 5번의 하계 올림픽과 4번의 동계 올림픽을 개최하면서 최다 올림픽을 개최한 나라이다. 영국은 2012년에 3번째 올림픽을 개최하였다. 독일, 오스트레일리아, 그리스는 하계 올림픽을 2번 개최한 국가이다. 동계 올림픽에서는 이탈리아가 2026년 밀라노-코르티나담페초 개최지로 선정되어 3번 개최될 예정이다. 또한 프랑스가 3번을 개최했으며 2024년 하계올림픽 개최예정으로 영국에 이번 두 번째로 한 도시에서 3번 올림픽 개최하며 하계올림픽3번 개최하였다. 프랑스는 동계, 하계 올림픽 각 3번씩 총 6번 개최로 9번으로 최다개최국인 미국 다음으로 두 번째로 많이 개최한 국가가 된다. 스위스, 오스트리아, 노르웨이, 일본, 이탈리아는 2번씩 개최했다. 일본은 하계,동계 각 2번씩 총 4번으로 미국, 프랑스 다음 세번째로 많이 개최한 국가이다. 2010년에 밴쿠버에서 열린 2010년 동계 올림픽은 캐나다에서 열리는 두 번째 동계 올림픽이고, 동/하계 올림픽을 합쳐 캐나다에서 3번째로 개최되는 올림픽이다.',
 '고대 올림피아 경기를 제대로 구현한 최초의 시도는 혁명 시대의 프랑스에서 1796년부터 1798년까지 3년동안 실시했던 프랑스 국내 올림픽인 \'공화국 올림픽\'(L\'Olympiade de la République)이었다. 이 대회의 종목 중에는 고대 그리스 올림피아 경기 때 행한 일부 종목도 있었다. 특히 1798년 공화국 올림픽 대회는 미터법을 최초로 스포츠에 도입시킨 대회이기도 하다. 이후 52년뒤인 1850년에는 잉글랜드 슈롭셔주의 웬록에서 올림픽급의 대회가 열리기 시작하였다. 이 대회는 1859년에 아테네에서 열렸을 때 웬록 올림픽으로 명칭이 변경되었으며 지금도 열리고 있다. 브룩스 박사는 1859년에 아테네에서 열린 올림픽 경기의 내용을 이후 경기에 채택하였다. 1866년 런던의 수정궁에서는 윌리엄 페니 브룩스가 영국의 국가 올림픽 대회를 만들었다.  \n1821년 그리스에서는 오스만 제국의 지배에 반기를 들고 독립 전쟁이 일어나면서, 이때부터 올림픽 부활에 대한 관심이 생겨났다. 시인이자 신문 편집자였던 파나요티스 수초스(Παναγιώτης Σούτσος)는 1833년에 출간한 자신의 시 \'망자(亡者)의 대화\'에서 최초로 올림픽 부활에 대한 제안을 내놓았다. 그리스의 부유한 박애주의자였던 에방겔리스 자파스(Ευαγγέλης Ζάππας)는 1859년에 아테네 시 광장에서 열린 "올림픽 경기(일명 자파스 올림픽)"를 후원하였다. 이 경기에는 그리스와 오스만 제국 출신의 선수들이 참가하였다. 에방겔리스 자파스는 이후에도 올림픽 경기를 개최할 수 있도록 고대의 경기장이었던 파나티네코 경기장을 복원하는 데도 돈을 썼다. 파나티네코 경기장에서 1870년과 1875년에 자파스 올림픽을 개최했으며, 현대 올림픽인 2004년 하계 올림픽 때는 양궁 경기장으로도 쓰였다.  \n역사학자였던 쿠베르탱은 프로이센-프랑스 전쟁(1870–1871)에서 프랑스의 패배 원인을 분석하면서 군사들이 체계적인 체력 훈련을 받지 않았기 때문에 전쟁에서 패배했다고 말한 인물이다. 1890년 웬록 올림픽에 참석한 쿠베르탱은 그 이후부터 올림픽을 대규모로 부활시킬 수 있으리라 생각했다. 쿠베르탱은 웬록 올림픽과 자파스 올림픽을 토대로 하여 올림픽 경기를 국제적으로 시행하기 위해 나라별로 올림픽을 번갈아가며 개최하는 방식을 생각해냈다. 그는 이 방안을 새로 설립된 국제 올림픽 위원회(IOC)의 첫 올림픽 의회 기간 중에 언급했다. 총회는 파리의 소르본 대학교에서 1894년 6월 16일부터 6월 23일까지 7일간 지속되었으며, 총회 마지막날, 2년 후인 1896년에 아테네에서 국제적 규모의 올림픽 대회를 열기로 결정되었다. IOC는 올림픽을 조직하는 데에 모든 책임을 졌으며, 초대 위원장으로는 그리스의 작가였던 디미트리오스 비켈라스(Δημήτριος Βικέλας)가 선출되었다.']

# RAGAS 를 이용해 평가를 위한 합성 데이터 셋 만들기

- 평가 데이터셋 구성
  - `user_input`: 사용자 질문
  - `retrieved_contexts`: Vectorstore에서 검색한 context
  - `response`: LLM의 응답
  - `reference`: 정답

## TestsetGenerator
- **문서(retrieved_contexts)를 기준**으로 **질문**, **정답** 을 생성한다.
- 평가할 LLM으로 생성된 질문을 넣어 답변을 추출하여 데이터셋을 구성한다.


> **주의**
> - TestsetGenerator import 시 `No Module named langchain_community.chat_models.vertexai` Error 발생 
> - RAGAS와 langchain-community의 버전 호환성 문제 때문에 발생한다.
> - 해결
>   1. langchain_google_vertexai 설치
>       - `!uv pip install langchain_google_vertexai`
>   2. `.venv\Lib\site-packages\langchain_community\chat_models` 디렉토리 아래 `vertexai.py` 파일을 만들고 아래 코드를 > 넣는다.
>    ```python
>       try:
>           from langchain_google_vertexai import ChatVertexAI
>       except ImportError:
>           class ChatVertexAI:
>               def __init__(self, *args, **kwargs):
>                   raise ImportError(
>                       "ChatVertexAI requires langchain-google-vertexai. "
>                       "Install with: pip install langchain-google-vertexai"
>                   )
>    ```

In [1]:
# 주피터노트북 환경에서 비동기적 처리 위해
# script(.py) 로 작성할 경우는 필요 없다.

import nest_asyncio
nest_asyncio.apply()

In [2]:
from ragas.testset import TestsetGenerator

In [ ]:
##################################################################################################
# testset -> Context들(문서들) - [질문 - 정답답변 + (Retriever가 찾은 문서 + LLM 정답: Chain 생성)]
# 1. Context(문서들)을 추출 -> TestsetGenerator -> 질문과 정답답변 생성.

import random
# 데이터셋을 생성할 때 사용할 Context를 추출.
client = QdrantClient(url="http://localhost:6333")
COLLECTION_NAME = "olympic_info_wiki"

# 전체 저장된 문서 중에서 K개만 sampling
info = client.get_collection(COLLECTION_NAME)
total_docs = info.points_count # 총 문서개수 조회

results, _ = client.scroll(
    collection_name= COLLECTION_NAME,
    limit = total_docs,
)
# 랜덤하게 K(5)개를 sampling
sample_docs:"list[PointStruct]" = random.sample(results, 5) # 리스트에서 랜덤하게 k(5)개를 추출 (k: 데이터셋 개수)

# PointStruct - payload: page_content, metadata
# page_content만 추출해서 list[str]
docs = [point.payload['page_content'] for point in sample_docs]

In [8]:
docs

["1950년대까지 IOC는 적은 예산으로 운영되어 왔다. 에이버리 브런디지가 위원장으로 있던 1952년부터 1972년까지, 에이버리 브런디지는 그 어떤 상업적인 관심도 올림픽과 연계를 꾀하는 것을 거부했다. 협력 스폰서의 관심이 IOC의 결정에 지나치게 간섭할 우려가 있다고 생각했기 때문이다. 브런디지가 이러한 수익창출을 거부했다는 것은 IOC가 스폰서 계약이나 올림픽 상징의 사용에 대한 협상을 포기했다는 뜻이다. 브런디지가 IOC에 200만 달러를 남기고 은퇴한 후 8년 뒤에 IOC의 잔고는 4500만 달러로 늘어났다. 그 이유는 IOC가 처음으로 텔레비전 중계권을 판매하고 스폰서와 계약함으로써 올림픽의 팽창을 노리는 이데올로기(관념)의 변화가 있었기 때문이다. 1980년에 IOC위원장으로 후안 안토니오 사마란치가 당선되었을 때, 그의 소원이 IOC의 재정적 독립이었을 정도로 상업성에 대한 시각도 많이 달라졌다.  \n1984년 하계 올림픽은 올림픽 역사에 있어서 획기적인 순간이었다. 피터 워버로스(Peter Ueberroth)의 지휘하에 있던 LA 하계 올림픽 조직위원회는 그 당시 2억 2500만 달러라는 전례가 없던 이익을 얻었다. 왜냐하면 조직위원회는 독점스폰서에 대한 권리를 판매하였고 그로 인해 이익을 창출할 수 있었기 때문이다. IOC는 이러한 재정적 후원 권리를 통제하기 위한 방법을 강구했다. 1년 뒤인 1985년 사마란치 IOC 위원장은 올림픽 브랜드를 만들어내기 위한 '올림픽 프로그램(The Olympic Program, TOP)'을 설립했다. TOP의 회원들은 '독점'적이고, '비싼 비용'을 IOC에 지불해야만 한다. 4년마다 TOP 회원들은 5000만 달러를 내야 한다. 그 대가로 TOP의 회원은 생산하는 물품에 올림픽 상징인 오륜기를 국제적, 독점적으로 사용하고 출판물이나 광고에도 이용할 수 있는 혜택을 누리게 된다.",
 "올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다.  \n#### 개막식  \n개막식 때는 올림픽 헌장에 따라 다양한 행사가 열린다. 개막식의 기본 토대는 벨기에 안트베르펜에서 열린 1920년 하계 올림픽 때 만들어졌다. 개막식은 대개 개최국의 국기가 게양되고 국가가 울려퍼지며 시작된다. 그 후에 개최국이 준비한 그들의 문화를 대표하는 음악, 춤, 영상 따위가 공연된다. 개막식은 아름답기가 매회가 지날수록 웅대해지고 복잡해지는데, 이는 전 대회보다 사람들의 기억에 오래도록 남기기 위함이다. 보도에 의하면 2008 베이징 올림픽 개막식 때 든 비용은 1억 달러로 그 대부분이 예술적인 부분에 들었다고 한다.  \n행사가 끝나면 다음에는 각국의 선수단이 입장한다. 올림픽의 발상지라는 영예를 가진 그리스가 전통적으로 맨 처음에 입장한다. 나머지 각국 선수단은 주최국에서 선택한 언어의 사전 순으로 입장하고 나서, 개최국 선수단이 제일 마지막에 입장한다. 그리스 아테네에서 열린 2004년 하계 올림픽에서는 그리스 국기가 맨 처음에 입장하고, 그리스 선수단이 맨 마지막에 입장했다. 개막식 마지막에는 올림픽 성화가 들어오고 마지막 성화 봉송자에게 전달할 때까지 돌게 된다. 마지막 성화 봉송자는 대체로 유명하고 올림픽에서 성공한 개최국의 선수가 하며 올림픽 성화를 경기장 내에 점화한다. 그 다음 올림픽조직위원장과 IOC 위원장이 개막 선언을 하는데 공식적으로 개막되었다는 것과 올림픽 성화가 점화되는 것을 선언한다. 그 다음에 올림픽조직위원장과 IOC 위원장이 개회사를 낭독하게 된다. 마자막으로 올림픽기 게양에 이어 올림픽 선서를 끝으로 개막식 과정은 모두 끝나게 된다. 2020년 하계 올림픽 이후로는 그리스 - 난민 올림픽 선수단 - 나머지 각국 선수단 - 차차기 올림픽 개최국 - 차기 올림픽 개최국 - 개최국 순서대로 입장한다.  \n#### 폐막식  \n폐막식은 올림픽 경기가 모두 끝난 후에 열린다. 각국의 기수가 경기장에 들어온 후에 국적에 상관없이 모든 선수들이 함께 들어온다. 3개의 기가 국가가 울려퍼지는 동안 게양되는데, 그 3개의 국기는 그리스의 국기(올림픽의 발상지임을 기념하기 위해), 개최도시의 국기, 다음 하계·동계 올림픽의 개최도시의 국기이다. 그 다음 올림픽조직위원장과 IOC 위원장이 폐막 선언을 하는데 공식적으로 폐막되었다는 것과 올림픽 성화가 꺼지는 것을 선언한다. 일명 '안트베르펜 세레모니'라고 하는 것도 진행되는데, 이는 올림픽 개최도시의 수장이 특별한 올림픽 기를 IOC 위원장에게 넘겨주면 그것을 또다시 다음 대회의 개최도시의 수장에게 넘겨주는 것으로서 1920 안트베르펜 올림픽 때부터 시작한 것으로 알려져 있다. 이 행사가 끝나면 짧게 다음 대회 개최지에 대한 소개로 홍보 영상이나 퍼포먼스가 진행된다.  \n#### 시상식  \n시상식은 각 종목이 끝날 때마다 열린다. 개인 혹은 팀으로 참가해서 1위를 하거나 2위 혹은 3위를 한 선수(들)은 시상대에 올라서서 존경의 뜻으로 메달을 수여받는다. 올림픽 위원들에게 메달을 받은 후에 1위를 한 선수의 국가가 울려퍼지고 1, 2, 3위를 한 선수들의 국기가 올라간다. 개최도시의 자원봉사자들도 시상식 때 활동하는데 메달을 준비하거나 꽃을 들고 이동하는 것과 같은 일을 한다. 올림픽 종목마다 시상식은 대체로 그 종목의 결승전(본선)이 끝난 후 거의 하루 뒤에 이루어진다. 남자 마라톤의 경우에는 시작은 올림픽 마지막 날 아침 일찍 하고 시상식은 그 날 저녁에 폐막식 도중에 이루어진다.",
 "올림픽 경기 종목은 총 33개부문 52개 종목에서 약 400개의 경기로 이루어져있다. 예를 들어서 하계 올림픽 부문인 레슬링은 자유형과 그레코로만형의 두 종목으로 나뉜다. 여기에서 10경기는 남자부, 4경기는 여자부로 열리며 분류기준은 체중이다. 하계 올림픽은 26개, 동계 올림픽은 7개 부문으로 이루어져있다. 하계 올림픽에서는 육상, 수영, 펜싱, 체조가 1회 대회때부터 한번도 빠짐없이 정식종목이었으며, 동계 올림픽에서는 크로스컨트리, 피겨 스케이팅, 아이스 하키, 노르딕 복합, 스키 점프, 스피드 스케이팅이 1924년 동계 올림픽부터 빠짐없이 정식종목이었다. 배드민턴, 농구, 배구와 같은 정식종목들은 처음에는 시범종목이었으며 그 후에 정식종목으로 승인 되었다. 야구처럼 예전에는 정식종목 이었지만 지금은 정식 종목에서 빠진 종목도 있다.  \n각 올림픽 종목들은 IOC로부터 승인을 받은 국제경기연맹의 관리를 받는다. 35개의 연맹이 IOC에서 승인을 받았으며, 승인을 받았지만 현재 정식종목이 아닌 종목을 감독하는 연맹도 있다. IOC의 승인을 받았지만 올림픽 종목이 아닌 스포츠들은 올림픽 종목으로 고려되지는 않으나, 올림픽이 끝난 후 처음으로 열리는 IOC총회 때마다 정식종목이 되도록 신청을 할 수는 있다. IOC 총회 때 정식종목 선정은 총회에 참석중인 IOC위원들의 투표를 통해 이루어지며, 재적 위원 수의 과반수 이상 찬성표를 얻어야 정식종목으로 인정을 받는다. IOC의 승인을 받은 스포츠이나 찬성표를 받지 못해 정식종목이 되지 못한 스포츠로는 체스와 서핑과 같은 것이 있다.  \n2004년 10월과 11월에 IOC는 '올림픽 프로그램 위원회'(Olympic Programme Commission)를 설립했다. 여기서는 올림픽 종목과 올림픽 종목이 아닌 스포츠를 모두 재검토하는 일을 한다. 이 위원회의 목표는 올림픽 종목에 더 체계적으로 다가가는 것이다. 위원회에서는 우선적으로 올림픽 종목으로 포함되기 위해서는 7개의 기준을 충족시켜야 한다고 말한다. 이 7개의 기준은 역사, 전통, 보편성, 인기도와 잠재성, 선수의 건강, 연맹의 스포츠를 관리할만한 능력, 스포츠를 여는 데에 필요한 비용이다. 예를 들면 2012년 하계 올림픽의 정식종목 후보에 7개 조건을 포함한 비(非)올림픽 스포츠가 올랐고 그 내용은, 골프, 가라테, 럭비, 인라인 스케이팅, 스쿼시였다. 이 스포츠들은 IOC 상임이사회에서 재검토되어 2005년 7월에 열린 싱가포르 총회에서 최종 결정하기로 했다. 결국 5개 중 2개(가라테와 스쿼시) 가 최종 후보로 올라왔으나 가라테와 스쿼시 둘 다 2/3의 미만의 찬성표로 정식종목이 되지는 못한다. 그 후 2016년 올림픽 정식종목에는 7개의 스포츠가 정식종목 신청을 했는데, 내용은 가라테, 골프, 스쿼시, 야구, 소프트볼, 7인제 럭비, 인라인 스케이팅이었다. 2009년 8월 13일, 신청된 7개의 스포츠 중 단 2개만 최종후보로 선정되었는데, 이는 7인제 럭비와 골프였다. 같은해인 2009년 10월에 열린 IOC 총회에서 골프와 럭비는 과반수 이상의 득표를 얻어서 2016년 하계 올림픽과 2020년 하계 올림픽의 정식종목으로 채택되었다.  \n2002년에 열린 제114차 IOC 총회에서는 하계 올림픽 종목은 최대 28부문 301개 경기에 10,500명이 참가하는 것으로 제한하기로 결정했다. 그 후 3년 뒤인 제117차 IOC 총회에서는 정식종목이었던 야구와 소프트볼을 정식 종목에서 제외시킨다. 이 결과에 대한 이견이 없었으므로 2012년 올림픽 때는 26개부문에서 경기가 열린다. 2016년과 2020년 올림픽 때는 럭비와 골프가 추가되어 다시 28개부문에서 경기가 열린다.",
 '올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.',
 '패럴림픽(Paralympic)은 신체·감각 장애가 있는운동 선수가 참가하는 국제 스포츠 대회로, 장애인 올림픽으로 불린다. 1948년에 루드비히 구트만 경(Sir Ludwig Guttman)은 제2차 세계대전에 참전한 군인들의 사회 복귀를 위한 일환으로 1948년 런던 올림픽과 동시에 몇몇 병원들을 연합해서 여러 경기를 펼쳤다. 구트만의 세계 휠체어, 신체부자유자대회(World Wheelchair and Amputee Games)로 알려진 이 대회는 매년 열리는 스포츠대회가 되었다. 12년이 넘도록 구트만과 다른 사람들은 스포츠를 상처를 치료하는 방법 중 하나로써 계속 대회 개최에 노력을 기울였다. 로마에서 열린 1960년 하계 올림픽때 구트만은 400명의 선수들을 "Parallel Olympics"에 참가시켰으며 이것이 곧 1회 패럴림픽으로 알려지게 되었다. 그 때부터 패럴림픽은 하계 올림픽이 열린 년도에 열리게 되었다. 서울에서 열린 1988년 하계 올림픽부터는 하계 올림픽을 개최한 도시는 패럴림픽도 같이 개최하기로 한다.']

In [10]:
total_docs
sample_docs

[Record(id='b87e4596-2048-4d85-aacd-8be8beb5ca14', payload={'page_content': "1950년대까지 IOC는 적은 예산으로 운영되어 왔다. 에이버리 브런디지가 위원장으로 있던 1952년부터 1972년까지, 에이버리 브런디지는 그 어떤 상업적인 관심도 올림픽과 연계를 꾀하는 것을 거부했다. 협력 스폰서의 관심이 IOC의 결정에 지나치게 간섭할 우려가 있다고 생각했기 때문이다. 브런디지가 이러한 수익창출을 거부했다는 것은 IOC가 스폰서 계약이나 올림픽 상징의 사용에 대한 협상을 포기했다는 뜻이다. 브런디지가 IOC에 200만 달러를 남기고 은퇴한 후 8년 뒤에 IOC의 잔고는 4500만 달러로 늘어났다. 그 이유는 IOC가 처음으로 텔레비전 중계권을 판매하고 스폰서와 계약함으로써 올림픽의 팽창을 노리는 이데올로기(관념)의 변화가 있었기 때문이다. 1980년에 IOC위원장으로 후안 안토니오 사마란치가 당선되었을 때, 그의 소원이 IOC의 재정적 독립이었을 정도로 상업성에 대한 시각도 많이 달라졌다.  \n1984년 하계 올림픽은 올림픽 역사에 있어서 획기적인 순간이었다. 피터 워버로스(Peter Ueberroth)의 지휘하에 있던 LA 하계 올림픽 조직위원회는 그 당시 2억 2500만 달러라는 전례가 없던 이익을 얻었다. 왜냐하면 조직위원회는 독점스폰서에 대한 권리를 판매하였고 그로 인해 이익을 창출할 수 있었기 때문이다. IOC는 이러한 재정적 후원 권리를 통제하기 위한 방법을 강구했다. 1년 뒤인 1985년 사마란치 IOC 위원장은 올림픽 브랜드를 만들어내기 위한 '올림픽 프로그램(The Olympic Program, TOP)'을 설립했다. TOP의 회원들은 '독점'적이고, '비싼 비용'을 IOC에 지불해야만 한다. 4년마다 TOP 회원들은 5000만 달러를 내야 한다. 그 대가로 TOP의 회원은 생산하는 물품에 올림픽 상징인 오륜기를 국제적, 독점적으로 사용하고 출판물이나 광고에도 이용할 수 있는 혜택을 누리게 된다.", 'metadata': {'H1': '올림픽', 'H2': '상업화', 'H3': '예산'}}, vector=None, shard_key=None, order_value=None),
 Record(id='f16d788e-de4a-4905-b6e1-b6fe2da676fa', payload={'page_content': "올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다.  \n#### 개막식  \n개막식 때는 올림픽 헌장에 따라 다양한 행사가 열린다. 개막식의 기본 토대는 벨기에 안트베르펜에서 열린 1920년 하계 올림픽 때 만들어졌다. 개막식은 대개 개최국의 국기가 게양되고 국가가 울려퍼지며 시작된다. 그 후에 개최국이 준비한 그들의 문화를 대표하는 음악, 춤, 영상 따위가 공연된다. 개막식은 아름답기가 매회가 지날수록 웅대해지고 복잡해지는데, 이는 전 대회보다 사람들의 기억에 오래도록 남기기 위함이다. 보도에 의하면 2008 베이징 올림픽 개막식 때 든 비용은 1억 달러로 그 대부분이 예술적인 부분에 들었다고 한다.  \n행사가 끝나면 다음에는 각국의 선수단이 입장한다. 올림픽의 발상지라는 영예를 가진 그리스가 전통적으로 맨 처음에 입장한다. 나머지 각국 선수단은 주최국에서 선택한 언어의 사전 순으로 입장하고 나서, 개최국 선수단이 제일 마지막에 입장한다. 그리스 아테네에서 열린 2004년 하계 올림픽에서는 그리스 국기가 맨 처음에 입장하고, 그리스 선수단이 맨 마지막에 입장했다. 개막식 마지막에는 올림픽 성화가 들어오고 마지막 성화 봉송자에게 전달할 때까지 돌게 된다. 마지막 성화 봉송자는 대체로 유명하고 올림픽에서 성공한 개최국의 선수가 하며 올림픽 성화를 경기장 내에 점화한다. 그 다음 올림픽조직위원장과 IOC 위원장이 개막 선언을 하는데 공식적으로 개막되었다는 것과 올림픽 성화가 점화되는 것을 선언한다. 그 다음에 올림픽조직위원장과 IOC 위원장이 개회사를 낭독하게 된다. 마자막으로 올림픽기 게양에 이어 올림픽 선서를 끝으로 개막식 과정은 모두 끝나게 된다. 2020년 하계 올림픽 이후로는 그리스 - 난민 올림픽 선수단 - 나머지 각국 선수단 - 차차기 올림픽 개최국 - 차기 올림픽 개최국 - 개최국 순서대로 입장한다.  \n#### 폐막식  \n폐막식은 올림픽 경기가 모두 끝난 후에 열린다. 각국의 기수가 경기장에 들어온 후에 국적에 상관없이 모든 선수들이 함께 들어온다. 3개의 기가 국가가 울려퍼지는 동안 게양되는데, 그 3개의 국기는 그리스의 국기(올림픽의 발상지임을 기념하기 위해), 개최도시의 국기, 다음 하계·동계 올림픽의 개최도시의 국기이다. 그 다음 올림픽조직위원장과 IOC 위원장이 폐막 선언을 하는데 공식적으로 폐막되었다는 것과 올림픽 성화가 꺼지는 것을 선언한다. 일명 '안트베르펜 세레모니'라고 하는 것도 진행되는데, 이는 올림픽 개최도시의 수장이 특별한 올림픽 기를 IOC 위원장에게 넘겨주면 그것을 또다시 다음 대회의 개최도시의 수장에게 넘겨주는 것으로서 1920 안트베르펜 올림픽 때부터 시작한 것으로 알려져 있다. 이 행사가 끝나면 짧게 다음 대회 개최지에 대한 소개로 홍보 영상이나 퍼포먼스가 진행된다.  \n#### 시상식  \n시상식은 각 종목이 끝날 때마다 열린다. 개인 혹은 팀으로 참가해서 1위를 하거나 2위 혹은 3위를 한 선수(들)은 시상대에 올라서서 존경의 뜻으로 메달을 수여받는다. 올림픽 위원들에게 메달을 받은 후에 1위를 한 선수의 국가가 울려퍼지고 1, 2, 3위를 한 선수들의 국기가 올라간다. 개최도시의 자원봉사자들도 시상식 때 활동하는데 메달을 준비하거나 꽃을 들고 이동하는 것과 같은 일을 한다. 올림픽 종목마다 시상식은 대체로 그 종목의 결승전(본선)이 끝난 후 거의 하루 뒤에 이루어진다. 남자 마라톤의 경우에는 시작은 올림픽 마지막 날 아침 일찍 하고 시상식은 그 날 저녁에 폐막식 도중에 이루어진다.", 'metadata': {'H1': '올림픽', 'H2': '상업화', 'H3': '행사'}}, vector=None, shard_key=None, order_value=None),
 Record(id='83370322-7683-49c7-803c-16154ccab49a', payload={'page_content': "올림픽 경기 종목은 총 33개부문 52개 종목에서 약 400개의 경기로 이루어져있다. 예를 들어서 하계 올림픽 부문인 레슬링은 자유형과 그레코로만형의 두 종목으로 나뉜다. 여기에서 10경기는 남자부, 4경기는 여자부로 열리며 분류기준은 체중이다. 하계 올림픽은 26개, 동계 올림픽은 7개 부문으로 이루어져있다. 하계 올림픽에서는 육상, 수영, 펜싱, 체조가 1회 대회때부터 한번도 빠짐없이 정식종목이었으며, 동계 올림픽에서는 크로스컨트리, 피겨 스케이팅, 아이스 하키, 노르딕 복합, 스키 점프, 스피드 스케이팅이 1924년 동계 올림픽부터 빠짐없이 정식종목이었다. 배드민턴, 농구, 배구와 같은 정식종목들은 처음에는 시범종목이었으며 그 후에 정식종목으로 승인 되었다. 야구처럼 예전에는 정식종목 이었지만 지금은 정식 종목에서 빠진 종목도 있다.  \n각 올림픽 종목들은 IOC로부터 승인을 받은 국제경기연맹의 관리를 받는다. 35개의 연맹이 IOC에서 승인을 받았으며, 승인을 받았지만 현재 정식종목이 아닌 종목을 감독하는 연맹도 있다. IOC의 승인을 받았지만 올림픽 종목이 아닌 스포츠들은 올림픽 종목으로 고려되지는 않으나, 올림픽이 끝난 후 처음으로 열리는 IOC총회 때마다 정식종목이 되도록 신청을 할 수는 있다. IOC 총회 때 정식종목 선정은 총회에 참석중인 IOC위원들의 투표를 통해 이루어지며, 재적 위원 수의 과반수 이상 찬성표를 얻어야 정식종목으로 인정을 받는다. IOC의 승인을 받은 스포츠이나 찬성표를 받지 못해 정식종목이 되지 못한 스포츠로는 체스와 서핑과 같은 것이 있다.  \n2004년 10월과 11월에 IOC는 '올림픽 프로그램 위원회'(Olympic Programme Commission)를 설립했다. 여기서는 올림픽 종목과 올림픽 종목이 아닌 스포츠를 모두 재검토하는 일을 한다. 이 위원회의 목표는 올림픽 종목에 더 체계적으로 다가가는 것이다. 위원회에서는 우선적으로 올림픽 종목으로 포함되기 위해서는 7개의 기준을 충족시켜야 한다고 말한다. 이 7개의 기준은 역사, 전통, 보편성, 인기도와 잠재성, 선수의 건강, 연맹의 스포츠를 관리할만한 능력, 스포츠를 여는 데에 필요한 비용이다. 예를 들면 2012년 하계 올림픽의 정식종목 후보에 7개 조건을 포함한 비(非)올림픽 스포츠가 올랐고 그 내용은, 골프, 가라테, 럭비, 인라인 스케이팅, 스쿼시였다. 이 스포츠들은 IOC 상임이사회에서 재검토되어 2005년 7월에 열린 싱가포르 총회에서 최종 결정하기로 했다. 결국 5개 중 2개(가라테와 스쿼시) 가 최종 후보로 올라왔으나 가라테와 스쿼시 둘 다 2/3의 미만의 찬성표로 정식종목이 되지는 못한다. 그 후 2016년 올림픽 정식종목에는 7개의 스포츠가 정식종목 신청을 했는데, 내용은 가라테, 골프, 스쿼시, 야구, 소프트볼, 7인제 럭비, 인라인 스케이팅이었다. 2009년 8월 13일, 신청된 7개의 스포츠 중 단 2개만 최종후보로 선정되었는데, 이는 7인제 럭비와 골프였다. 같은해인 2009년 10월에 열린 IOC 총회에서 골프와 럭비는 과반수 이상의 득표를 얻어서 2016년 하계 올림픽과 2020년 하계 올림픽의 정식종목으로 채택되었다.  \n2002년에 열린 제114차 IOC 총회에서는 하계 올림픽 종목은 최대 28부문 301개 경기에 10,500명이 참가하는 것으로 제한하기로 결정했다. 그 후 3년 뒤인 제117차 IOC 총회에서는 정식종목이었던 야구와 소프트볼을 정식 종목에서 제외시킨다. 이 결과에 대한 이견이 없었으므로 2012년 올림픽 때는 26개부문에서 경기가 열린다. 2016년과 2020년 올림픽 때는 럭비와 골프가 추가되어 다시 28개부문에서 경기가 열린다.", 'metadata': {'H1': '올림픽', 'H2': '올림픽 경기 종목'}}, vector=None, shard_key=None, order_value=None),
 Record(id='1cc5be3e-f190-4927-8a4e-2b8f213e177c', payload={'page_content': '올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.', 'metadata': {'H1': '올림픽', 'H2': '상업화', 'H3': '상징'}}, vector=None, shard_key=None, order_value=None),
 Record(id='7ee920e6-fbc7-43bd-8f4d-8a6558623ab7', payload={'page_content': '패럴림픽(Paralympic)은 신체·감각 장애가 있는운동 선수가 참가하는 국제 스포츠 대회로, 장애인 올림픽으로 불린다. 1948년에 루드비히 구트만 경(Sir Ludwig Guttman)은 제2차 세계대전에 참전한 군인들의 사회 복귀를 위한 일환으로 1948년 런던 올림픽과 동시에 몇몇 병원들을 연합해서 여러 경기를 펼쳤다. 구트만의 세계 휠체어, 신체부자유자대회(World Wheelchair and Amputee Games)로 알려진 이 대회는 매년 열리는 스포츠대회가 되었다. 12년이 넘도록 구트만과 다른 사람들은 스포츠를 상처를 치료하는 방법 중 하나로써 계속 대회 개최에 노력을 기울였다. 로마에서 열린 1960년 하계 올림픽때 구트만은 400명의 선수들을 "Parallel Olympics"에 참가시켰으며 이것이 곧 1회 패럴림픽으로 알려지게 되었다. 그 때부터 패럴림픽은 하계 올림픽이 열린 년도에 열리게 되었다. 서울에서 열린 1988년 하계 올림픽부터는 하계 올림픽을 개최한 도시는 패럴림픽도 같이 개최하기로 한다.', 'metadata': {'H1': '올림픽', 'H2': '근대 올림픽', 'H3': '패럴림픽'}}, vector=None, shard_key=None, order_value=None)]

In [11]:
# 테스트 셋을 생성
from ragas.testset import TestsetGenerator
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

from langchain_openai import OpenAI, OpenAIEmbeddings
# TestsetGenerator는 gpt-5 이후 버전은 사용할 수 없다. (호환성 문제 / Temp)
## Langchain의 LLM 모델과 Embedding 모델 -> RAGAS에서 사용할 수 있도록 변환 (Wrapping)
generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

generator = TestsetGenerator(
    llm= generator_llm,
    embedding_model = generator_embeddings,
    llm_context="""
- 사람들이 올림픽에 대해서 궁금해 할 만한 질문들을 생성한다.
- 데이터셋은 반드시 한국어로 작성한다.
- 데이터셋은 JSON 문법을 지켜서 작성한다. 특히 구두점은 꼭 지켜야 한다.
- 생성된 내용이나 Document에 JSON 문법에 맞지 않는 표현이 있으면 반드시 수정해서 처리한다.
""" # 질문/답변을 생성할 때 LLM에게 전달할 System Prompt를 설정.
)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_23384\3545982627.py:9: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
C:\Users\Playdata\AppData\Local\Temp\ipykernel_23384\3545982627.py:10: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

In [12]:
testset = generator.generate_with_chunks(
    docs, testset_size=10, # Context 내용, 테스트셋 개수 (질문-답변 개수)
)

Applying SummaryExtractor:   0%|          | 0/5 [00:00<?, ?it/s]

Applying CustomNodeFilter:   0%|          | 0/5 [00:00<?, ?it/s]

Node 0a113584-e02f-4398-b028-e990e72926da does not have a summary. Skipping filtering.
Node 960706e9-1e28-4949-98b6-b7f199ee5661 does not have a summary. Skipping filtering.
Node c049f95f-522f-4bca-9713-bfcddfe091b0 does not have a summary. Skipping filtering.
Node 44afef2c-6c11-4d34-90bf-4203c0dd20cc does not have a summary. Skipping filtering.
Node 72c731f5-9bb2-45df-9c78-a4b272666444 does not have a summary. Skipping filtering.

Applying EmbeddingExtractor:   0%|          | 0/5 [00:00<?, ?it/s]

Applying ThemesExtractor:   0%|          | 0/5 [00:00<?, ?it/s]

Applying NERExtractor:   0%|          | 0/5 [00:00<?, ?it/s]

Applying CosineSimilarityBuilder:   0%|          | 0/1 [00:00<?, ?it/s]

Applying OverlapScoreBuilder:   0%|          | 0/1 [00:00<?, ?it/s]

Skipping multi_hop_abstract_query_synthesizer due to unexpected error: No relationships match the provided condition. Cannot form clusters.

Generating personas:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Scenarios:   0%|          | 0/2 [00:00<?, ?it/s]

Generating Samples:   0%|          | 0/10 [00:00<?, ?it/s]

In [13]:
testset

Testset(samples=[TestsetSample(eval_sample=SingleTurnSample(user_input='후안 안토니오 사마란치가 IOC 위원장으로 당선된 후 올림픽 상업성에 어떤 변화가 있었나요?', retrieved_contexts=None, reference_contexts=["1950년대까지 IOC는 적은 예산으로 운영되어 왔다. 에이버리 브런디지가 위원장으로 있던 1952년부터 1972년까지, 에이버리 브런디지는 그 어떤 상업적인 관심도 올림픽과 연계를 꾀하는 것을 거부했다. 협력 스폰서의 관심이 IOC의 결정에 지나치게 간섭할 우려가 있다고 생각했기 때문이다. 브런디지가 이러한 수익창출을 거부했다는 것은 IOC가 스폰서 계약이나 올림픽 상징의 사용에 대한 협상을 포기했다는 뜻이다. 브런디지가 IOC에 200만 달러를 남기고 은퇴한 후 8년 뒤에 IOC의 잔고는 4500만 달러로 늘어났다. 그 이유는 IOC가 처음으로 텔레비전 중계권을 판매하고 스폰서와 계약함으로써 올림픽의 팽창을 노리는 이데올로기(관념)의 변화가 있었기 때문이다. 1980년에 IOC위원장으로 후안 안토니오 사마란치가 당선되었을 때, 그의 소원이 IOC의 재정적 독립이었을 정도로 상업성에 대한 시각도 많이 달라졌다.  \n1984년 하계 올림픽은 올림픽 역사에 있어서 획기적인 순간이었다. 피터 워버로스(Peter Ueberroth)의 지휘하에 있던 LA 하계 올림픽 조직위원회는 그 당시 2억 2500만 달러라는 전례가 없던 이익을 얻었다. 왜냐하면 조직위원회는 독점스폰서에 대한 권리를 판매하였고 그로 인해 이익을 창출할 수 있었기 때문이다. IOC는 이러한 재정적 후원 권리를 통제하기 위한 방법을 강구했다. 1년 뒤인 1985년 사마란치 IOC 위원장은 올림픽 브랜드를 만들어내기 위한 '올림픽 프로그램(The Olympic Program, TOP)'을 설립했다. TOP의 회원들은 '독점'적이고, '비싼 비용'을 IOC에 지불해야만 한다. 4년마다 TOP 회원들은 5000만 달러를 내야 한다. 그 대가로 TOP의 회원은 생산하는 물품에 올림픽 상징인 오륜기를 국제적, 독점적으로 사용하고 출판물이나 광고에도 이용할 수 있는 혜택을 누리게 된다."], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference="1980년에 IOC위원장으로 후안 안토니오 사마란치가 당선되었을 때, 그의 소원이 IOC의 재정적 독립이었을 정도로 상업성에 대한 시각도 많이 달라졌다. 1985년 사마란치 IOC 위원장은 올림픽 브랜드를 만들어내기 위한 '올림픽 프로그램(The Olympic Program, TOP)'을 설립했다. TOP의 회원들은 '독점'적이고, '비싼 비용'을 IOC에 지불해야만 한다. 4년마다 TOP 회원들은 5000만 달러를 내야 한다. 그 대가로 TOP의 회원은 생산하는 물품에 올림픽 상징인 오륜기를 국제적, 독점적으로 사용하고 출판물이나 광고에도 이용할 수 있는 혜택을 누리게 된다.", rubrics=None, persona_name='Sports Business Analyst', query_style='MISSPELLED', query_length='MEDIUM'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='아테네 올림픽 개막식에서 그리스 선수단의 입장 순서는 어떻게 되었나요?', retrieved_contexts=None, reference_contexts=["올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다.  \n#### 개막식  \n개막식 때는 올림픽 헌장에 따라 다양한 행사가 열린다. 개막식의 기본 토대는 벨기에 안트베르펜에서 열린 1920년 하계 올림픽 때 만들어졌다. 개막식은 대개 개최국의 국기가 게양되고 국가가 울려퍼지며 시작된다. 그 후에 개최국이 준비한 그들의 문화를 대표하는 음악, 춤, 영상 따위가 공연된다. 개막식은 아름답기가 매회가 지날수록 웅대해지고 복잡해지는데, 이는 전 대회보다 사람들의 기억에 오래도록 남기기 위함이다. 보도에 의하면 2008 베이징 올림픽 개막식 때 든 비용은 1억 달러로 그 대부분이 예술적인 부분에 들었다고 한다.  \n행사가 끝나면 다음에는 각국의 선수단이 입장한다. 올림픽의 발상지라는 영예를 가진 그리스가 전통적으로 맨 처음에 입장한다. 나머지 각국 선수단은 주최국에서 선택한 언어의 사전 순으로 입장하고 나서, 개최국 선수단이 제일 마지막에 입장한다. 그리스 아테네에서 열린 2004년 하계 올림픽에서는 그리스 국기가 맨 처음에 입장하고, 그리스 선수단이 맨 마지막에 입장했다. 개막식 마지막에는 올림픽 성화가 들어오고 마지막 성화 봉송자에게 전달할 때까지 돌게 된다. 마지막 성화 봉송자는 대체로 유명하고 올림픽에서 성공한 개최국의 선수가 하며 올림픽 성화를 경기장 내에 점화한다. 그 다음 올림픽조직위원장과 IOC 위원장이 개막 선언을 하는데 공식적으로 개막되었다는 것과 올림픽 성화가 점화되는 것을 선언한다. 그 다음에 올림픽조직위원장과 IOC 위원장이 개회사를 낭독하게 된다. 마자막으로 올림픽기 게양에 이어 올림픽 선서를 끝으로 개막식 과정은 모두 끝나게 된다. 2020년 하계 올림픽 이후로는 그리스 - 난민 올림픽 선수단 - 나머지 각국 선수단 - 차차기 올림픽 개최국 - 차기 올림픽 개최국 - 개최국 순서대로 입장한다.  \n#### 폐막식  \n폐막식은 올림픽 경기가 모두 끝난 후에 열린다. 각국의 기수가 경기장에 들어온 후에 국적에 상관없이 모든 선수들이 함께 들어온다. 3개의 기가 국가가 울려퍼지는 동안 게양되는데, 그 3개의 국기는 그리스의 국기(올림픽의 발상지임을 기념하기 위해), 개최도시의 국기, 다음 하계·동계 올림픽의 개최도시의 국기이다. 그 다음 올림픽조직위원장과 IOC 위원장이 폐막 선언을 하는데 공식적으로 폐막되었다는 것과 올림픽 성화가 꺼지는 것을 선언한다. 일명 '안트베르펜 세레모니'라고 하는 것도 진행되는데, 이는 올림픽 개최도시의 수장이 특별한 올림픽 기를 IOC 위원장에게 넘겨주면 그것을 또다시 다음 대회의 개최도시의 수장에게 넘겨주는 것으로서 1920 안트베르펜 올림픽 때부터 시작한 것으로 알려져 있다. 이 행사가 끝나면 짧게 다음 대회 개최지에 대한 소개로 홍보 영상이나 퍼포먼스가 진행된다.  \n#### 시상식  \n시상식은 각 종목이 끝날 때마다 열린다. 개인 혹은 팀으로 참가해서 1위를 하거나 2위 혹은 3위를 한 선수(들)은 시상대에 올라서서 존경의 뜻으로 메달을 수여받는다. 올림픽 위원들에게 메달을 받은 후에 1위를 한 선수의 국가가 울려퍼지고 1, 2, 3위를 한 선수들의 국기가 올라간다. 개최도시의 자원봉사자들도 시상식 때 활동하는데 메달을 준비하거나 꽃을 들고 이동하는 것과 같은 일을 한다. 올림픽 종목마다 시상식은 대체로 그 종목의 결승전(본선)이 끝난 후 거의 하루 뒤에 이루어진다. 남자 마라톤의 경우에는 시작은 올림픽 마지막 날 아침 일찍 하고 시상식은 그 날 저녁에 폐막식 도중에 이루어진다."], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='그리스 아테네에서 열린 2004년 하계 올림픽에서는 그리스 국기가 맨 처음에 입장하고, 그리스 선수단이 맨 마지막에 입장했습니다.', rubrics=None, persona_name='Olympics Enthusiast', query_style='MISSPELLED', query_length='MEDIUM'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='동계 올림픽 뭐뭐 있나, 몇 개 부문 있고 언제부터 어떤 종목 계속 있었는지, 그리고 동계 올림픽 종목 정해지는 기준 뭐임, IOC가 어떻게 정식종목 정하는지 궁금함.', retrieved_contexts=None, reference_contexts=["올림픽 경기 종목은 총 33개부문 52개 종목에서 약 400개의 경기로 이루어져있다. 예를 들어서 하계 올림픽 부문인 레슬링은 자유형과 그레코로만형의 두 종목으로 나뉜다. 여기에서 10경기는 남자부, 4경기는 여자부로 열리며 분류기준은 체중이다. 하계 올림픽은 26개, 동계 올림픽은 7개 부문으로 이루어져있다. 하계 올림픽에서는 육상, 수영, 펜싱, 체조가 1회 대회때부터 한번도 빠짐없이 정식종목이었으며, 동계 올림픽에서는 크로스컨트리, 피겨 스케이팅, 아이스 하키, 노르딕 복합, 스키 점프, 스피드 스케이팅이 1924년 동계 올림픽부터 빠짐없이 정식종목이었다. 배드민턴, 농구, 배구와 같은 정식종목들은 처음에는 시범종목이었으며 그 후에 정식종목으로 승인 되었다. 야구처럼 예전에는 정식종목 이었지만 지금은 정식 종목에서 빠진 종목도 있다.  \n각 올림픽 종목들은 IOC로부터 승인을 받은 국제경기연맹의 관리를 받는다. 35개의 연맹이 IOC에서 승인을 받았으며, 승인을 받았지만 현재 정식종목이 아닌 종목을 감독하는 연맹도 있다. IOC의 승인을 받았지만 올림픽 종목이 아닌 스포츠들은 올림픽 종목으로 고려되지는 않으나, 올림픽이 끝난 후 처음으로 열리는 IOC총회 때마다 정식종목이 되도록 신청을 할 수는 있다. IOC 총회 때 정식종목 선정은 총회에 참석중인 IOC위원들의 투표를 통해 이루어지며, 재적 위원 수의 과반수 이상 찬성표를 얻어야 정식종목으로 인정을 받는다. IOC의 승인을 받은 스포츠이나 찬성표를 받지 못해 정식종목이 되지 못한 스포츠로는 체스와 서핑과 같은 것이 있다.  \n2004년 10월과 11월에 IOC는 '올림픽 프로그램 위원회'(Olympic Programme Commission)를 설립했다. 여기서는 올림픽 종목과 올림픽 종목이 아닌 스포츠를 모두 재검토하는 일을 한다. 이 위원회의 목표는 올림픽 종목에 더 체계적으로 다가가는 것이다. 위원회에서는 우선적으로 올림픽 종목으로 포함되기 위해서는 7개의 기준을 충족시켜야 한다고 말한다. 이 7개의 기준은 역사, 전통, 보편성, 인기도와 잠재성, 선수의 건강, 연맹의 스포츠를 관리할만한 능력, 스포츠를 여는 데에 필요한 비용이다. 예를 들면 2012년 하계 올림픽의 정식종목 후보에 7개 조건을 포함한 비(非)올림픽 스포츠가 올랐고 그 내용은, 골프, 가라테, 럭비, 인라인 스케이팅, 스쿼시였다. 이 스포츠들은 IOC 상임이사회에서 재검토되어 2005년 7월에 열린 싱가포르 총회에서 최종 결정하기로 했다. 결국 5개 중 2개(가라테와 스쿼시) 가 최종 후보로 올라왔으나 가라테와 스쿼시 둘 다 2/3의 미만의 찬성표로 정식종목이 되지는 못한다. 그 후 2016년 올림픽 정식종목에는 7개의 스포츠가 정식종목 신청을 했는데, 내용은 가라테, 골프, 스쿼시, 야구, 소프트볼, 7인제 럭비, 인라인 스케이팅이었다. 2009년 8월 13일, 신청된 7개의 스포츠 중 단 2개만 최종후보로 선정되었는데, 이는 7인제 럭비와 골프였다. 같은해인 2009년 10월에 열린 IOC 총회에서 골프와 럭비는 과반수 이상의 득표를 얻어서 2016년 하계 올림픽과 2020년 하계 올림픽의 정식종목으로 채택되었다.  \n2002년에 열린 제114차 IOC 총회에서는 하계 올림픽 종목은 최대 28부문 301개 경기에 10,500명이 참가하는 것으로 제한하기로 결정했다. 그 후 3년 뒤인 제117차 IOC 총회에서는 정식종목이었던 야구와 소프트볼을 정식 종목에서 제외시킨다. 이 결과에 대한 이견이 없었으므로 2012년 올림픽 때는 26개부문에서 경기가 열린다. 2016년과 2020년 올림픽 때는 럭비와 골프가 추가되어 다시 28개부문에서 경기가 열린다."], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='동계 올림픽은 7개 부문으로 이루어져 있고, 크로스컨트리, 피겨 스케이팅, 아이스 하키, 노르딕 복합, 스키 점프, 스피드 스케이팅이 1924년 동계 올림픽부터 빠짐없이 정식종목이었다. 올림픽 종목은 IOC로부터 승인을 받은 국제경기연맹의 관리를 받으며, 정식종목 선정은 IOC 총회에서 재적 위원 수의 과반수 이상 찬성표를 얻어야 정식종목으로 인정을 받는다. 또, 올림픽 프로그램 위원회에서는 올림픽 종목으로 포함되기 위해 7개의 기준(역사, 전통, 보편성, 인기도와 잠재성, 선수의 건강, 연맹의 스포츠 관리 능력, 스포츠 개최 비용)을 충족해야 한다고 한다.', rubrics=None, persona_name='Olympics Enthusiast', query_style='POOR_GRAMMAR', query_length='LONG'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='올림픽 성화와 그리스의 관계는 무엇이며, 성화가 어떻게 채화되는지 설명해 주세요.', retrieved_contexts=None, reference_contexts=['올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='매 올림픽이 시작되기 몇 개월 전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화됩니다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화합니다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달됩니다.', rubrics=None, persona_name='Sports Business Analyst', query_style='PERFECT_GRAMMAR', query_length='LONG'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='1948년 런던 올림픽 그때 뭐 있었고 왜 중요한지 설명해줘, 잘 모르겠는데 그때 무슨 일 있었는지 자세히 말해줘.', retrieved_contexts=None, reference_contexts=['패럴림픽(Paralympic)은 신체·감각 장애가 있는운동 선수가 참가하는 국제 스포츠 대회로, 장애인 올림픽으로 불린다. 1948년에 루드비히 구트만 경(Sir Ludwig Guttman)은 제2차 세계대전에 참전한 군인들의 사회 복귀를 위한 일환으로 1948년 런던 올림픽과 동시에 몇몇 병원들을 연합해서 여러 경기를 펼쳤다. 구트만의 세계 휠체어, 신체부자유자대회(World Wheelchair and Amputee Games)로 알려진 이 대회는 매년 열리는 스포츠대회가 되었다. 12년이 넘도록 구트만과 다른 사람들은 스포츠를 상처를 치료하는 방법 중 하나로써 계속 대회 개최에 노력을 기울였다. 로마에서 열린 1960년 하계 올림픽때 구트만은 400명의 선수들을 "Parallel Olympics"에 참가시켰으며 이것이 곧 1회 패럴림픽으로 알려지게 되었다. 그 때부터 패럴림픽은 하계 올림픽이 열린 년도에 열리게 되었다. 서울에서 열린 1988년 하계 올림픽부터는 하계 올림픽을 개최한 도시는 패럴림픽도 같이 개최하기로 한다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='1948년에 루드비히 구트만 경은 제2차 세계대전에 참전한 군인들의 사회 복귀를 위해 1948년 런던 올림픽과 동시에 여러 병원들을 연합해서 여러 경기를 펼쳤다. 이 대회는 구트만의 세계 휠체어, 신체부자유자대회로 알려졌고, 매년 열리는 스포츠대회가 되었다. 이 대회는 장애인 올림픽, 즉 패럴림픽의 시작점이 되었으며, 이후 구트만과 다른 사람들은 스포츠를 상처를 치료하는 방법으로 계속 대회를 개최했다.', rubrics=None, persona_name='Olympic Sports Program Coordinator', query_style='POOR_GRAMMAR', query_length='LONG'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='올림픽 상징인 오륜기가 상업적으로 어떻게 활용되었으며, 오륜기의 의미는 무엇인가?', retrieved_contexts=None, reference_contexts=["<1-hop>\n\n1950년대까지 IOC는 적은 예산으로 운영되어 왔다. 에이버리 브런디지가 위원장으로 있던 1952년부터 1972년까지, 에이버리 브런디지는 그 어떤 상업적인 관심도 올림픽과 연계를 꾀하는 것을 거부했다. 협력 스폰서의 관심이 IOC의 결정에 지나치게 간섭할 우려가 있다고 생각했기 때문이다. 브런디지가 이러한 수익창출을 거부했다는 것은 IOC가 스폰서 계약이나 올림픽 상징의 사용에 대한 협상을 포기했다는 뜻이다. 브런디지가 IOC에 200만 달러를 남기고 은퇴한 후 8년 뒤에 IOC의 잔고는 4500만 달러로 늘어났다. 그 이유는 IOC가 처음으로 텔레비전 중계권을 판매하고 스폰서와 계약함으로써 올림픽의 팽창을 노리는 이데올로기(관념)의 변화가 있었기 때문이다. 1980년에 IOC위원장으로 후안 안토니오 사마란치가 당선되었을 때, 그의 소원이 IOC의 재정적 독립이었을 정도로 상업성에 대한 시각도 많이 달라졌다.  \n1984년 하계 올림픽은 올림픽 역사에 있어서 획기적인 순간이었다. 피터 워버로스(Peter Ueberroth)의 지휘하에 있던 LA 하계 올림픽 조직위원회는 그 당시 2억 2500만 달러라는 전례가 없던 이익을 얻었다. 왜냐하면 조직위원회는 독점스폰서에 대한 권리를 판매하였고 그로 인해 이익을 창출할 수 있었기 때문이다. IOC는 이러한 재정적 후원 권리를 통제하기 위한 방법을 강구했다. 1년 뒤인 1985년 사마란치 IOC 위원장은 올림픽 브랜드를 만들어내기 위한 '올림픽 프로그램(The Olympic Program, TOP)'을 설립했다. TOP의 회원들은 '독점'적이고, '비싼 비용'을 IOC에 지불해야만 한다. 4년마다 TOP 회원들은 5000만 달러를 내야 한다. 그 대가로 TOP의 회원은 생산하는 물품에 올림픽 상징인 오륜기를 국제적, 독점적으로 사용하고 출판물이나 광고에도 이용할 수 있는 혜택을 누리게 된다.", '<2-hop>\n\n올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='올림픽 상징인 오륜기는 1985년 IOC가 설립한 올림픽 프로그램(TOP)을 통해 상업적으로 활용되기 시작했다. TOP 회원들은 높은 비용을 지불하고 오륜기를 국제적, 독점적으로 사용할 수 있는 권리를 얻어 출판물이나 광고 등에서 활용할 수 있다. 오륜기는 5개의 둥근 고리가 얽혀 있으며, 각 원은 5대륙을 상징한다. 파랑, 노랑, 검정, 초록, 빨간 고리와 흰색 바탕은 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문에 선택되었다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='1920년 하계 올림픽 개막식이랑 폐막식에서 시작된 전통은 뭐에요?', retrieved_contexts=None, reference_contexts=["<1-hop>\n\n올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다.  \n#### 개막식  \n개막식 때는 올림픽 헌장에 따라 다양한 행사가 열린다. 개막식의 기본 토대는 벨기에 안트베르펜에서 열린 1920년 하계 올림픽 때 만들어졌다. 개막식은 대개 개최국의 국기가 게양되고 국가가 울려퍼지며 시작된다. 그 후에 개최국이 준비한 그들의 문화를 대표하는 음악, 춤, 영상 따위가 공연된다. 개막식은 아름답기가 매회가 지날수록 웅대해지고 복잡해지는데, 이는 전 대회보다 사람들의 기억에 오래도록 남기기 위함이다. 보도에 의하면 2008 베이징 올림픽 개막식 때 든 비용은 1억 달러로 그 대부분이 예술적인 부분에 들었다고 한다.  \n행사가 끝나면 다음에는 각국의 선수단이 입장한다. 올림픽의 발상지라는 영예를 가진 그리스가 전통적으로 맨 처음에 입장한다. 나머지 각국 선수단은 주최국에서 선택한 언어의 사전 순으로 입장하고 나서, 개최국 선수단이 제일 마지막에 입장한다. 그리스 아테네에서 열린 2004년 하계 올림픽에서는 그리스 국기가 맨 처음에 입장하고, 그리스 선수단이 맨 마지막에 입장했다. 개막식 마지막에는 올림픽 성화가 들어오고 마지막 성화 봉송자에게 전달할 때까지 돌게 된다. 마지막 성화 봉송자는 대체로 유명하고 올림픽에서 성공한 개최국의 선수가 하며 올림픽 성화를 경기장 내에 점화한다. 그 다음 올림픽조직위원장과 IOC 위원장이 개막 선언을 하는데 공식적으로 개막되었다는 것과 올림픽 성화가 점화되는 것을 선언한다. 그 다음에 올림픽조직위원장과 IOC 위원장이 개회사를 낭독하게 된다. 마자막으로 올림픽기 게양에 이어 올림픽 선서를 끝으로 개막식 과정은 모두 끝나게 된다. 2020년 하계 올림픽 이후로는 그리스 - 난민 올림픽 선수단 - 나머지 각국 선수단 - 차차기 올림픽 개최국 - 차기 올림픽 개최국 - 개최국 순서대로 입장한다.  \n#### 폐막식  \n폐막식은 올림픽 경기가 모두 끝난 후에 열린다. 각국의 기수가 경기장에 들어온 후에 국적에 상관없이 모든 선수들이 함께 들어온다. 3개의 기가 국가가 울려퍼지는 동안 게양되는데, 그 3개의 국기는 그리스의 국기(올림픽의 발상지임을 기념하기 위해), 개최도시의 국기, 다음 하계·동계 올림픽의 개최도시의 국기이다. 그 다음 올림픽조직위원장과 IOC 위원장이 폐막 선언을 하는데 공식적으로 폐막되었다는 것과 올림픽 성화가 꺼지는 것을 선언한다. 일명 '안트베르펜 세레모니'라고 하는 것도 진행되는데, 이는 올림픽 개최도시의 수장이 특별한 올림픽 기를 IOC 위원장에게 넘겨주면 그것을 또다시 다음 대회의 개최도시의 수장에게 넘겨주는 것으로서 1920 안트베르펜 올림픽 때부터 시작한 것으로 알려져 있다. 이 행사가 끝나면 짧게 다음 대회 개최지에 대한 소개로 홍보 영상이나 퍼포먼스가 진행된다.  \n#### 시상식  \n시상식은 각 종목이 끝날 때마다 열린다. 개인 혹은 팀으로 참가해서 1위를 하거나 2위 혹은 3위를 한 선수(들)은 시상대에 올라서서 존경의 뜻으로 메달을 수여받는다. 올림픽 위원들에게 메달을 받은 후에 1위를 한 선수의 국가가 울려퍼지고 1, 2, 3위를 한 선수들의 국기가 올라간다. 개최도시의 자원봉사자들도 시상식 때 활동하는데 메달을 준비하거나 꽃을 들고 이동하는 것과 같은 일을 한다. 올림픽 종목마다 시상식은 대체로 그 종목의 결승전(본선)이 끝난 후 거의 하루 뒤에 이루어진다. 남자 마라톤의 경우에는 시작은 올림픽 마지막 날 아침 일찍 하고 시상식은 그 날 저녁에 폐막식 도중에 이루어진다."], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference="1920년 하계 올림픽 개막식에서는 개막식의 기본 토대가 만들어졌고, 폐막식에서는 개최도시의 수장이 올림픽 기를 IOC 위원장에게 넘겨주고 다시 다음 대회의 개최도시 수장에게 넘겨주는 '안트베르펜 세레모니'가 시작되었습니다.", rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='1984년 하계 올림픽이 올림픽의 상업화와 재정 구조에 어떤 변화를 가져왔으며, 이 변화가 이후 IOC의 올림픽 프로그램(TOP) 설립에 어떻게 연결되었는지 설명해 주세요.', retrieved_contexts=None, reference_contexts=["<1-hop>\n\n1950년대까지 IOC는 적은 예산으로 운영되어 왔다. 에이버리 브런디지가 위원장으로 있던 1952년부터 1972년까지, 에이버리 브런디지는 그 어떤 상업적인 관심도 올림픽과 연계를 꾀하는 것을 거부했다. 협력 스폰서의 관심이 IOC의 결정에 지나치게 간섭할 우려가 있다고 생각했기 때문이다. 브런디지가 이러한 수익창출을 거부했다는 것은 IOC가 스폰서 계약이나 올림픽 상징의 사용에 대한 협상을 포기했다는 뜻이다. 브런디지가 IOC에 200만 달러를 남기고 은퇴한 후 8년 뒤에 IOC의 잔고는 4500만 달러로 늘어났다. 그 이유는 IOC가 처음으로 텔레비전 중계권을 판매하고 스폰서와 계약함으로써 올림픽의 팽창을 노리는 이데올로기(관념)의 변화가 있었기 때문이다. 1980년에 IOC위원장으로 후안 안토니오 사마란치가 당선되었을 때, 그의 소원이 IOC의 재정적 독립이었을 정도로 상업성에 대한 시각도 많이 달라졌다.  \n1984년 하계 올림픽은 올림픽 역사에 있어서 획기적인 순간이었다. 피터 워버로스(Peter Ueberroth)의 지휘하에 있던 LA 하계 올림픽 조직위원회는 그 당시 2억 2500만 달러라는 전례가 없던 이익을 얻었다. 왜냐하면 조직위원회는 독점스폰서에 대한 권리를 판매하였고 그로 인해 이익을 창출할 수 있었기 때문이다. IOC는 이러한 재정적 후원 권리를 통제하기 위한 방법을 강구했다. 1년 뒤인 1985년 사마란치 IOC 위원장은 올림픽 브랜드를 만들어내기 위한 '올림픽 프로그램(The Olympic Program, TOP)'을 설립했다. TOP의 회원들은 '독점'적이고, '비싼 비용'을 IOC에 지불해야만 한다. 4년마다 TOP 회원들은 5000만 달러를 내야 한다. 그 대가로 TOP의 회원은 생산하는 물품에 올림픽 상징인 오륜기를 국제적, 독점적으로 사용하고 출판물이나 광고에도 이용할 수 있는 혜택을 누리게 된다."], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference="1984년 하계 올림픽은 LA 하계 올림픽 조직위원회가 독점스폰서 권리를 판매하여 2억 2500만 달러라는 전례 없는 이익을 얻으면서 올림픽 역사상 상업화와 재정 구조에 획기적인 변화를 가져왔습니다. 이 성공을 바탕으로 IOC는 재정적 후원 권리를 통제하기 위한 방법을 모색하였고, 1985년 사마란치 IOC 위원장은 올림픽 브랜드를 만들어내기 위해 '올림픽 프로그램(TOP)'을 설립했습니다. TOP 회원들은 높은 비용을 지불하고 올림픽 상징을 독점적으로 사용할 수 있는 권리를 얻게 되었으며, 이는 올림픽의 상업화와 재정적 독립을 더욱 강화하는 계기가 되었습니다.", rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='1960년 하계 올림픽과 관련하여 패럴림픽의 시작과 그 이후 올림픽 개최 도시와의 관계에 대해 설명해 주세요.', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n패럴림픽(Paralympic)은 신체·감각 장애가 있는운동 선수가 참가하는 국제 스포츠 대회로, 장애인 올림픽으로 불린다. 1948년에 루드비히 구트만 경(Sir Ludwig Guttman)은 제2차 세계대전에 참전한 군인들의 사회 복귀를 위한 일환으로 1948년 런던 올림픽과 동시에 몇몇 병원들을 연합해서 여러 경기를 펼쳤다. 구트만의 세계 휠체어, 신체부자유자대회(World Wheelchair and Amputee Games)로 알려진 이 대회는 매년 열리는 스포츠대회가 되었다. 12년이 넘도록 구트만과 다른 사람들은 스포츠를 상처를 치료하는 방법 중 하나로써 계속 대회 개최에 노력을 기울였다. 로마에서 열린 1960년 하계 올림픽때 구트만은 400명의 선수들을 "Parallel Olympics"에 참가시켰으며 이것이 곧 1회 패럴림픽으로 알려지게 되었다. 그 때부터 패럴림픽은 하계 올림픽이 열린 년도에 열리게 되었다. 서울에서 열린 1988년 하계 올림픽부터는 하계 올림픽을 개최한 도시는 패럴림픽도 같이 개최하기로 한다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference="패럴림픽은 1960년 로마에서 열린 하계 올림픽 때 루드비히 구트만이 400명의 선수들을 'Parallel Olympics'에 참가시키면서 1회 대회가 시작되었습니다. 이후 패럴림픽은 하계 올림픽이 열리는 해에 함께 개최되었으며, 1988년 서울 하계 올림픽부터는 올림픽을 개최한 도시가 패럴림픽도 같이 개최하기로 하였습니다.", rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='올림픽 개막식과 폐막식에서 그리스가 어떤 특별한 역할을 하며, 이러한 전통이 올림픽의 상징과 어떻게 연결되어 있는지 설명하시오.', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.', "<2-hop>\n\n올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다.  \n#### 개막식  \n개막식 때는 올림픽 헌장에 따라 다양한 행사가 열린다. 개막식의 기본 토대는 벨기에 안트베르펜에서 열린 1920년 하계 올림픽 때 만들어졌다. 개막식은 대개 개최국의 국기가 게양되고 국가가 울려퍼지며 시작된다. 그 후에 개최국이 준비한 그들의 문화를 대표하는 음악, 춤, 영상 따위가 공연된다. 개막식은 아름답기가 매회가 지날수록 웅대해지고 복잡해지는데, 이는 전 대회보다 사람들의 기억에 오래도록 남기기 위함이다. 보도에 의하면 2008 베이징 올림픽 개막식 때 든 비용은 1억 달러로 그 대부분이 예술적인 부분에 들었다고 한다.  \n행사가 끝나면 다음에는 각국의 선수단이 입장한다. 올림픽의 발상지라는 영예를 가진 그리스가 전통적으로 맨 처음에 입장한다. 나머지 각국 선수단은 주최국에서 선택한 언어의 사전 순으로 입장하고 나서, 개최국 선수단이 제일 마지막에 입장한다. 그리스 아테네에서 열린 2004년 하계 올림픽에서는 그리스 국기가 맨 처음에 입장하고, 그리스 선수단이 맨 마지막에 입장했다. 개막식 마지막에는 올림픽 성화가 들어오고 마지막 성화 봉송자에게 전달할 때까지 돌게 된다. 마지막 성화 봉송자는 대체로 유명하고 올림픽에서 성공한 개최국의 선수가 하며 올림픽 성화를 경기장 내에 점화한다. 그 다음 올림픽조직위원장과 IOC 위원장이 개막 선언을 하는데 공식적으로 개막되었다는 것과 올림픽 성화가 점화되는 것을 선언한다. 그 다음에 올림픽조직위원장과 IOC 위원장이 개회사를 낭독하게 된다. 마자막으로 올림픽기 게양에 이어 올림픽 선서를 끝으로 개막식 과정은 모두 끝나게 된다. 2020년 하계 올림픽 이후로는 그리스 - 난민 올림픽 선수단 - 나머지 각국 선수단 - 차차기 올림픽 개최국 - 차기 올림픽 개최국 - 개최국 순서대로 입장한다.  \n#### 폐막식  \n폐막식은 올림픽 경기가 모두 끝난 후에 열린다. 각국의 기수가 경기장에 들어온 후에 국적에 상관없이 모든 선수들이 함께 들어온다. 3개의 기가 국가가 울려퍼지는 동안 게양되는데, 그 3개의 국기는 그리스의 국기(올림픽의 발상지임을 기념하기 위해), 개최도시의 국기, 다음 하계·동계 올림픽의 개최도시의 국기이다. 그 다음 올림픽조직위원장과 IOC 위원장이 폐막 선언을 하는

In [20]:
sample1 = testset.samples[9].eval_sample # 10개중 첫번째 테스트 데이터
print("사용자 질문:", sample1.user_input)
print("Context:", sample1.reference_contexts) # 질문과 답변을 만들 때 사용한 context (검색시 찾아야 하는 문서)
print("생성된 답변(정답):", sample1.reference)

##### 평가 대상 RAG System을 이용해서 채워 넣어야 한다.
print("평가대상 RAG의 답변:", sample1.response)
print("평가대상 RAG가 검색한 Context:", sample1.retrieved_contexts)

사용자 질문: 올림픽 개막식과 폐막식에서 그리스가 어떤 특별한 역할을 하며, 이러한 전통이 올림픽의 상징과 어떻게 연결되어 있는지 설명하시오.
Context: ['<1-hop>\n\n올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.', "<2-hop>\n\n올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다.  \n#### 개막식  \n개막식 때는 올림픽 헌장에 따라 다양한 행사가 열린다. 개막식의 기본 토대는 벨기에 안트베르펜에서 열린 1920년 하계 올림픽 때 만들어졌다. 개막식은 대개 개최국의 국기가 게양되고 국가가 울려퍼지며 시작된다. 그 후에 개최국이 준비한 그들의 문화를 대표하는 음악, 춤, 영상 따위가 공연된다. 개막식은 아름답기가 매회가 지날수록 웅대해지고 복잡해지는데, 이는 전 대회보다 사람들의 기억에 오래도록 남기기 위함이다. 보도에 의하면 2008 베이징 올림픽 개막식 때 든 비용은 1억 달러로 그 대부분이 예술적인 부분에 들었다고 한다.  \n행사가 끝나면 다음에는 각국의 선수단이 입장한다. 올림픽의 발상지라는 영예를 가진 그리스가 전통적으로 맨 처음에 입장한다. 나머지 각국 선수단은 주최국에서 선택한 언어의 사전 순으로 입장하고 나서, 개최국 선수단이 제일 마지막에 입장한다. 그리스 아테네에서 열린 2004년 하계 올림픽에서는 그리스 국기가 맨 처음에 입장하고, 그리스 선수단이 맨 마지막에 입장했다. 개막식 마지막에는 올림픽 성화가 들어오고 마지막 성화 봉송자에게 전달할 때까지 돌게 된다. 마지막 성화 봉송자는 대체로 유명하고 올림픽에서 성공한 개최국의 선수가 하며 올림픽 성화를 경기장 내에 점화한다. 그 다음 올림픽조직위원장과 IOC 위원장이 개막 선언을 하는데 공식적으로 개막되었다는 것과 올림픽 성화가 점화되는 것을 선언한다. 그 다음에 올림픽조직위원장과 IOC 위원장이 개회사를 낭독하게 된다. 마자막으로 올림픽기 게양에 이어 올림픽 선서를 끝으로 개막식 과정은 모두 끝나게 된다. 2020년 하계 올림픽 이후로는 그리스 - 난민 올림픽 선수단 - 나머지 각국 선수단 - 차차기 올림픽 개최국 - 차기 올림픽 개최국 - 개최국 순서대로 입장한다.  \n#### 폐막식  \n폐막식은 올림픽 경기가 모두 끝난 후에 열린다. 각국의 기수가 경기장에 들어온 후에 국적에 상관없이 모든 선수들이 함께 들어온다. 3개의 기가 국가가 울려퍼지는 동안 게양되는데, 그 3개의 국기는 그리스의 국기(올림픽의 발상지임을 기념하기 위해), 개최도시의 국기, 다음 하계·동계 올림픽의 개최도시의 국기이다. 그 다음 올림픽조직위원장과 IOC 위원장이 폐막 선언을 하는데 공식적으로 폐막되었다는 것과 올림픽 성화가 꺼지는 것을 선언한다. 일명 '안트베르펜 세레모니'라고 하는 것도 진행되는데, 이는 올림픽 개최도시의 수장이 특별한 올림픽 기를 IOC 위원장에게 넘겨주면 그것을 또다시 다음 대회의 개최도시의 수장에게 넘겨주는 것으로서 1920 안트베르펜 올림픽 때부터 시작한 것으로 알려져 있다. 이 행사가 끝나면 짧게 다음 대회 개최지에 대한 소개로 홍보 영상이나 퍼포먼스가 진행된다.  \n#### 시상식  \n시상식은 각 종목이 끝날 때마다 열린다. 개인 혹은 팀으로 참가해서 1위를 하거나 2위 혹은 3위를 한 선수(들)은 시상대에 올라서서 존경의 뜻으로 메달을 수여받는다. 올림픽 위원들에게 메달을 받은 후에 1위를 한 선수의 국가가 울려퍼지고 1, 2, 3위를 한 선수들의 국기가 올라간다. 개최도시의 자원봉사자들도 시상식 때 활동하는데 메달을 준비하거나 꽃을 들고 이동하는 것과 같은 일을 한다. 올림픽 종목마다 시상식은 대체로 그 종목의 결승전(본선)이 끝난 후 거의 하루 뒤에 이루어진다. 남자 마라톤의 경우에는 시작은 올림픽 마지막 날 아침 일찍 하고 시상식은 그 날 저녁에 폐막식 도중에 이루어진다."]
생성된 답변(정답): 올림픽 개막식에서는 올림픽의 발상지라는 영예를 가진 그리스가 전통적으로 맨 처음에 입장합니다. 2020년 하계 올림픽 이후로는 그리스가 가장 먼저 입장하고, 이어서 난민 올림픽 선수단, 나머지 각국 선수단, 차차기 및 차기 개최국, 마지막으로 개최국이 입장합니다. 폐막식에서는 3개의 국기가 게양되는데, 그 중 하나가 그리스의 국기로, 올림픽의 발상지임을 기념하기 위해서입니다. 이러한 전통은 올림픽의 상징과도 연결되어 있는데, 매 올림픽이 시작되기 전 고대 그리스의 올림피아에서 올림픽 성화가 채화되어 개최도시까지 전달되는 등, 그리스는 올림픽의 역사와 상징에서 중요한 역할을 하고 있습니다.
평가대상 RAG의 답변: None
평가대상 RAG가 검색한 Context: None

In [21]:
# 생성된 Testset을 Pandas DataFrame으로 변환

eval_df = testset.to_pandas()
eval_df.shape

(10, 7)

In [22]:
eval_df.head(3)

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name
0,후안 안토니오 사마란치가 IOC 위원장으로 당선된 후 올림픽 상업성에 어떤 변화가 ...,[1950년대까지 IOC는 적은 예산으로 운영되어 왔다. 에이버리 브런디지가 위원장...,"1980년에 IOC위원장으로 후안 안토니오 사마란치가 당선되었을 때, 그의 소원이 ...",Sports Business Analyst,MISSPELLED,MEDIUM,single_hop_specific_query_synthesizer
1,아테네 올림픽 개막식에서 그리스 선수단의 입장 순서는 어떻게 되었나요?,"[올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다. \n#...",그리스 아테네에서 열린 2004년 하계 올림픽에서는 그리스 국기가 맨 처음에 입장하...,Olympics Enthusiast,MISSPELLED,MEDIUM,single_hop_specific_query_synthesizer
2,"동계 올림픽 뭐뭐 있나, 몇 개 부문 있고 언제부터 어떤 종목 계속 있었는지, 그리...",[올림픽 경기 종목은 총 33개부문 52개 종목에서 약 400개의 경기로 이루어져있...,"동계 올림픽은 7개 부문으로 이루어져 있고, 크로스컨트리, 피겨 스케이팅, 아이스 ...",Olympics Enthusiast,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer

In [31]:
row_idx = 0
q = eval_df.loc[row_idx, 'user_input']
resp = chain.invoke(q) # dict[response, retrieved_context]

In [33]:
resp['response']

'후안 안토니오 사마란치가 IOC 위원장으로 당선된 1980년대부터 올림픽은 **상업성을 받아들이는 방향으로 변화**하기 시작했습니다.  \n구체적으로는 **국제적인 스폰서를 맞아들여 올림픽 관련 상품과 올림픽 브랜드를 연계**시키는 방식으로 바뀌었고, 1985년에는 **‘올림픽 프로그램(TOP)’**을 설립해 올림픽 상징의 독점적 사용과 스폰서 계약을 본격화했습니다.'

In [32]:
resp['retrieved_context']

['처음에 IOC는 스폰서에게서 자금제공을 받는 것을 거부했었다. 이런 방침은 에이버리 브런디지가 IOC 위원장이었던 1972년까지 유지되어 왔었다. 이 당시 IOC는 텔레비전 같은 미디어들이 갖는 잠재성과 큰 수익을 가져오는 광고시장에 대해 조사했었다. 그 후 1980년대 후안 안토니오 사마란치 위원장 시절부터 올림픽은 올림픽 관련 상품과 올림픽 브랜드를 연계시키려는 국제적인 스폰서를 맞아들임으로써 변화가 시작되었다.',
 "1950년대까지 IOC는 적은 예산으로 운영되어 왔다. 에이버리 브런디지가 위원장으로 있던 1952년부터 1972년까지, 에이버리 브런디지는 그 어떤 상업적인 관심도 올림픽과 연계를 꾀하는 것을 거부했다. 협력 스폰서의 관심이 IOC의 결정에 지나치게 간섭할 우려가 있다고 생각했기 때문이다. 브런디지가 이러한 수익창출을 거부했다는 것은 IOC가 스폰서 계약이나 올림픽 상징의 사용에 대한 협상을 포기했다는 뜻이다. 브런디지가 IOC에 200만 달러를 남기고 은퇴한 후 8년 뒤에 IOC의 잔고는 4500만 달러로 늘어났다. 그 이유는 IOC가 처음으로 텔레비전 중계권을 판매하고 스폰서와 계약함으로써 올림픽의 팽창을 노리는 이데올로기(관념)의 변화가 있었기 때문이다. 1980년에 IOC위원장으로 후안 안토니오 사마란치가 당선되었을 때, 그의 소원이 IOC의 재정적 독립이었을 정도로 상업성에 대한 시각도 많이 달라졌다.  \n1984년 하계 올림픽은 올림픽 역사에 있어서 획기적인 순간이었다. 피터 워버로스(Peter Ueberroth)의 지휘하에 있던 LA 하계 올림픽 조직위원회는 그 당시 2억 2500만 달러라는 전례가 없던 이익을 얻었다. 왜냐하면 조직위원회는 독점스폰서에 대한 권리를 판매하였고 그로 인해 이익을 창출할 수 있었기 때문이다. IOC는 이러한 재정적 후원 권리를 통제하기 위한 방법을 강구했다. 1년 뒤인 1985년 사마란치 IOC 위원장은 올림픽 브랜드를 만들어내기 위한 '올림픽 프로그램(The Olympic Program, TOP)'을 설립했다. TOP의 회원들은 '독점'적이고, '비싼 비용'을 IOC에 지불해야만 한다. 4년마다 TOP 회원들은 5000만 달러를 내야 한다. 그 대가로 TOP의 회원은 생산하는 물품에 올림픽 상징인 오륜기를 국제적, 독점적으로 사용하고 출판물이나 광고에도 이용할 수 있는 혜택을 누리게 된다.",
 "국제 올림픽 위원회(이하 IOC로 지칭)는 몇몇 위원들이 한 행위에 대해서 비판을 받고 있다. 그 예로 IOC 위원장이었던 에이버리 브런디지와 후안 안토니오 사마란치가 대표적인 사람이다. 브런디지는 20년 넘게 IOC 위원장직을 맡았고 임기 중에 올림픽을 정치적으로 휘말려들지 않게 하기 위해 보호했다. 그러나 그는 남아프리카 공화국 대표단에게 아파르트헤이트와 관련된 이슈를 건드리고 반유대정책을 함으로써 비난을 받았다. 사마란치 위원장 시기 때는 족벌 정치와 부패로 비난받았다. 사마란치가 스페인에서 프랑코 정권에 협력했다는 것도 비판의 이유가 되었다.  \n1998년에 몇몇 IOC위원들이 2002년 솔트레이크 시티 동계 올림픽 유치 과정에서 미국에게 미국을 올림픽 개최지로 뽑아달라는 뇌물청탁을 받았다는 것이 폭로되었다. 이에 IOC는 사퇴한 IOC위원 4명과 강제 퇴출된 6명에 대한 조사를 했다. 이 스캔들은 이후에 개최지 선정에서 이와 같은 불미스러운 일이 일어나지 않게 하기 위해서 IOC가 개혁에 착수하도록 하는 긍정적인 역할을 하기도 했다.  \nBBC 다큐멘터리인 '파노라마'에서는 '매수된 올림픽'이란 주제로 2004년 8월에 방송을 내보내기도 했다. 이때 이 프로그램에서는 2012년 하계 올림픽의 개최지 선정과 관련된 뇌물에 대해서 조사했다. 이 다큐멘터리에서는 특정 후보 도시가 IOC 위원들에게 뇌물수수하는 것이 가능했다고 주장했으며, 특히 파리 시장이었던 베르트랑 들라노에(Bertrand Delanoë)는 영국의 총리인 토니 블레어와 런던올림픽유치위원회가 입후보 규정을 위반했다고 비난했다. 그는 당시 프랑스 대통령이었던 자크 시라크를 목격자로 내세웠지만 시라크 대통령은 이 분쟁에 휘말려드는 것을 주의했으며 인터뷰를 삼갔다. 결국 베르트랑 들라노에의 주장에 대한 조사는 체계적으로 이루어지지는 않았다. 2006년 동계 올림픽을 유치했던 토리노도 이 논쟁에서 빠져나갈 수 없었다. 이번에는 스위스 국적의 IOC위원 마크 호들러(Marc Hodler)가 이 논쟁의 중심이 되었는데, 이 위원은 스위스 시온의 경쟁 도시였던 토리노가 IOC위원들에게 뇌물수수를 했다고 말했고, 이 발언으로 광범위한 조사가 이루어졌다. 이 언행이 많은 IOC위원들이 시온에 대해 언짢게 생각하게 되고 토리노가 개최지로 선정되도록 도와주는 역할을 했을 가능성도 제기되고 있다.",
 '올림픽 브랜드의 판매는 항상 논란이 되어왔다. 비판 중 하나는 올림픽이 지나치게 상업성과 연계되어 이제 올림픽이 기존의 상업적인 스포츠쇼와 다를 게 없다는 것이다. 1996년과 2000년 하계 올림픽 기간 사이에는 올림픽 관련 상품 시장의 포화 상태가 일어나면서 IOC에게 또 다른 비판이 일었다. 개최도시가 올림픽 관련 물건들을 파려는 상인과 회사들로 넘쳐났던 것이다. IOC는 이에 대해 앞으로 다가올 올림픽에서는 과다 경쟁을 방지하고 이런 불미스라운 상황이 일어나지 않도록 대처하겠다고 응답했다. 또 다른 비판으로는, 개최국이나 개최도시는 올림픽에 모든 비용을 들이는데 IOC는 손도 까딱 않고 올림픽 상징으로부터 얻는 모든 권리와 수입을 독차지하고 있다는 점이다. IOC는 올림픽 상징으로 인한 수입 뿐 아니라 스폰서와 중계권에서 들어오는 수입의 일정 지분도 가져간다. 개최도시 입장에서는 그들의 투자가 흑자가 될지 확신하지도 못하는 상황에서 올림픽 개최도시로서의 권리를 위해 노력을 해야 한다.',
 '베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이지만 텔레비전으로 방송한 첫 번째 올림픽이었다. 1956년 동계 올림픽은 올림픽을 전 세계적으로 중계 방송한 첫 번째 올림픽이었으며, 1960년 동계 올림픽에서는 중계권을 어느 특정한 방송사에 판매한첫 번째 올림픽이다. 그 후 수십 년간 올림픽은 냉전중인 국가들의 이데올로기 선전의 장이 되었다. 강대국들은 정치 주권을 위해 IOC(국제 올림픽 위원회)를 조종했으며, IOC는 중계권 판매를 통해 이익을 높이고자 하였다. 중계권의 판매는 올림픽을 전 세계적으로 알리는 데 큰 기여를 했으며, 그로 인해 텔레비전의 광고 시간을 사는 광고주들에게 경쟁을 유발하여 IOC는 더욱더 많은 이익을 얻게 되었다. 이는 IOC에게 있는 중계권을 비롯한 수많은 권리들에 지불해야 할 금액들이 앞으로도 지속적으로 늘어나게 됨을 의미한다. 예를 들면 1998년 동계 올림픽 중계권을 사는 데 CBS는 3억 7500만 달러를 지불했지만 2000~2012년 올림픽의 중계권을 따내는 데 NBC는 35억 달러나 지불해야 했다.  \n올림픽 시청자들 또한 1960년대부터 기하급수적으로 증가했다. 1968년 하계 올림픽을 텔레비전으로 시청한 사람들은 6억 명으로 추측되었고, 1984년 하계 올림픽을 시청한 사람들은 9억 명으로 늘어났으며, 1992년 하계 올림픽은 약 35억 명이 시청한 것으로 추측되고 있다. 하지만 NBC의 조사에 의하면 시드니에서 열린 2000년 하계 올림픽은 1968년부터 개최된 올림픽 중에서 가장 적은 수의 사람들이 시청한 것으로 조사되었다. 시청자 수 감소의 원인으로 크게 두 가지가 지목되는데, 그중 하나는 케이블 채널 간의 경쟁이 심화된 것이고, 다른 하나는 실시간으로 경기 영상과 결과를 보여주는 인터넷의 대중화이다. 이러한 원인 분석에도 불구하고 텔레비전 방송국들은 아직도 지연방송에 의존하고 있다. 시청률 감소를 다르게 표현하자면 텔레비전 방송국에서는 광고 시간을 예전보다 싼 가격에 제공할 수밖에 없다는 것을 의미하기도 한다. 텔레비전 방송국들은 국제 올림픽 위원회에게 많은 방송 비용과 인터넷의 발달로 인한 케이블의 치열한 경쟁을 이유로 엄청난 중계권 가격을 조금 낮춰달라고 요구하고 있다. 결국 IOC는 올림픽 프로그램 진행 시간을 상당 부분 변경하게 된다. 예를 들면 하계 올림픽 때 체조종목은 밤 7시에서 9시까지 하는 것으로 바뀌었으며, 갈라쇼는 흥미를 높이는 데에 초점을 맞추게 되었다. 또한 IOC는 수영과 다이빙 종목의 시간은 늘렸는데, 이 종목은 텔레비전 시청자들 중 가장 인기가 있는 종목 중 하나이기 때문이다. 이는 미국 방송국들의 로비가 올림픽 종목들의 일정 시간까지도 미국의 텔레비전 황금시간대에 맞춰서 변경될 수 있음을 의미하는 것이었다. 이 변화는 장점과 단점이 혼재되어 있고, 그 예로 유럽에서 열렸던 2006년 동계 올림픽의 시청률은 미국 솔트레이크 시티에서 열렸던 2002년 동계 올림픽과 비교해보면 확연히 낮았으며 또한 베이징에서 열렸던 2008년 하계 올림픽의 시청자는 급격히 늘어났다.']

In [36]:
# testset의 모든 데이터에 대한 llm 응답과 retriever의 검색 결과를 추가.
response_list = [] # LLM 응답들을 저장할 리스트
retrieved_context_list = [] # retriever가 검색한 문서들을 저장할 리스트

for user_input in eval_df['user_input']:
    resp = chain.invoke(user_input)
    response_list.append(resp['response'])
    retrieved_context_list.append(resp['retrieved_context'])

In [38]:
print(len(response_list), len(retrieved_context_list))

10 10

In [40]:
response_list

['후안 안토니오 사마란치가 IOC 위원장으로 당선된 뒤, 올림픽은 **상업성을 받아들이는 방향으로 변화**했습니다.  \n구체적으로는 **국제적 스폰서를 받아들이고**, **올림픽 관련 상품과 올림픽 브랜드를 연계**시키는 움직임이 시작되었습니다. 또한 **텔레비전 중계권 판매와 스폰서 계약**을 통해 재정적 독립과 수익 창출을 추구하게 되었습니다.',
 '정보가 부족해 답을 할 수없습니다.',
 '동계 올림픽에 대한 내용은 context에 다음과 같이 있습니다.\n\n- **동계 올림픽은 7개 부문**으로 이루어져 있습니다.\n- **1924년 동계 올림픽부터 빠짐없이 정식종목이었던 종목**은 다음 6개입니다:\n  - 크로스컨트리\n  - 피겨 스케이팅\n  - 아이스 하키\n  - 노르딕 복합\n  - 스키 점프\n  - 스피드 스케이팅\n\n- **동계 올림픽 종목이 정해지는 기준**에 대해서는, context에는 동계 종목에 대한 별도 선정 기준은 직접적으로 적혀 있지 않고, 올림픽 종목 전반에 대한 기준만 나와 있습니다.  \n  IOC 산하 **올림픽 프로그램 위원회**는 올림픽 종목 포함 여부를 판단할 때 다음 **7가지 기준**을 제시합니다:\n  1. 역사\n  2. 전통\n  3. 보편성\n  4. 인기도와 잠재성\n  5. 선수의 건강\n  6. 연맹의 스포츠 관리 능력\n  7. 스포츠를 여는 데 필요한 비용\n\n- **IOC가 정식종목을 정하는 방식**은 다음과 같습니다:\n  - 올림픽 끝난 뒤 처음 열리는 **IOC 총회** 때마다 정식종목 신청이 가능함\n  - **IOC 위원들의 투표**로 결정됨\n  - **재적 위원 수의 과반수 이상 찬성표**를 얻어야 정식종목으로 인정됨\n\n즉, context 기준으로 보면 동계 올림픽의 기본 정보는 위와 같고, 종목 채택 방식은 IOC 총회 투표와 과반수 찬성입니다.',
 '올림픽 성화는 **매 올림픽이 시작되기 몇 개월 전, 고대 그리스의 올림피아에서 채화**됩니다. 이는 **고대 그리스에서 제사를 지냈던 올림피아**와 연결되어 있습니다.\n\n채화 방법은 다음과 같습니다.\n- **여자 배우가 여자 사제처럼 연기**합니다.\n- **태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중**시켜 불을 붙입니다.\n- 그 후 **첫 번째 성화 봉송 주자에게 성화를 넘기고**, 이후 여러 사람의 손을 거쳐 **개최도시의 올림픽 경기장까지 전달**됩니다.\n\n즉, 올림픽 성화는 **그리스의 올림피아에서 시작되는 상징**이며, 채화는 **태양빛을 거울로 모아 점화하는 방식**으로 이루어집니다.',
 '정보가 부족해 답을 할 수없습니다.',
 '오륜기는 상업적으로는 IOC가 **올림픽 브랜드와 함께 독점적으로 사용·판매되는 상징**으로 활용되었고, TOP 회원들은 **4년마다 5000만 달러를 내는 대가로** 생산하는 물품, 출판물, 광고에 **올림픽 상징인 오륜기를 국제적·독점적으로 사용할 수 있는 혜택**을 받았습니다.  \n\n오륜기의 의미는 **5개의 고리가 얽혀 있으며 각 고리가 5대륙을 상징**한다는 것입니다. 또한 **파랑, 노랑, 검정, 초록, 빨간색과 흰 바탕**은 올림픽 기를 나타내며, 이 색들은 **모든 국기에서 적어도 하나 이상 포함되는 색들**이기 때문에 선택되었습니다.',
 '정보가 부족해 답을 할 수없습니다.',
 '1984년 하계 올림픽은 올림픽의 **상업화와 재정 구조가 크게 바뀐 획기적인 전환점**이었습니다.\n\n- LA 올림픽 조직위원회는 **독점 스폰서 권리 판매**를 통해 당시로서는 전례 없는 **2억 2500만 달러의 이익**을 얻었습니다.\n- 이는 올림픽이 단순한 스포츠 행사가 아니라, **스폰서 계약과 브랜드 활용을 통해 수익을 창출할 수 있는 구조**로 바뀌었음을 보여주었습니다.\n- 이 변화는 IOC가 기존의 소극적인 재정 운영 방식에서 벗어나, **올림픽을 통한 수익 확대와 재정적 독립**을 추구하게 만드는 계기가 되었습니다.\n\n이 흐름 속에서 IOC는 1985년, 사마란치 위원장 시절에 **올림픽 프로그램(TOP, The Olympic Program)** 을 설립했습니다.\n\n- TOP은 **올림픽 브랜드를 체계적으로 상품화**하기 위한 제도였습니다.\n- 회원 기업들은 IOC에 **비싼 비용**을 내고,\n- 그 대가로 **오륜기와 같은 올림픽 상징을 국제적으로 독점 사용**할 수 있는 권리를 얻었습니다.\n- 또한 제품, 출판물, 광고에 올림픽 상징을 사용할 수 있었습니다.\n\n즉, **1984년 올림픽의 대규모 흑자와 독점 스폰서 모델이 IOC로 하여금 공식적인 글로벌 스폰서 제도인 TOP를 만들게 한 직접적 배경**이 되었습니다.',
 '1960년 로마에서 열린 하계 올림픽 때, 루드비히 구트만이 400명의 선수들을 “Parallel Olympics”에 참가시켰고, 이것이 곧 1회 패럴림픽으로 알려지게 되었습니다.  \n\n그 이후 패럴림픽은 하계 올림픽이 열린 해에 함께 열리게 되었고, 1988년 서울 하계 올림픽부터는 하계 올림픽을 개최한 도시가 패럴림픽도 함께 개최하기로 하였습니다.',
 '정보가 부족해 답을 할 수없습니다.']

In [41]:
retrieved_context_list

[['처음에 IOC는 스폰서에게서 자금제공을 받는 것을 거부했었다. 이런 방침은 에이버리 브런디지가 IOC 위원장이었던 1972년까지 유지되어 왔었다. 이 당시 IOC는 텔레비전 같은 미디어들이 갖는 잠재성과 큰 수익을 가져오는 광고시장에 대해 조사했었다. 그 후 1980년대 후안 안토니오 사마란치 위원장 시절부터 올림픽은 올림픽 관련 상품과 올림픽 브랜드를 연계시키려는 국제적인 스폰서를 맞아들임으로써 변화가 시작되었다.',
  "1950년대까지 IOC는 적은 예산으로 운영되어 왔다. 에이버리 브런디지가 위원장으로 있던 1952년부터 1972년까지, 에이버리 브런디지는 그 어떤 상업적인 관심도 올림픽과 연계를 꾀하는 것을 거부했다. 협력 스폰서의 관심이 IOC의 결정에 지나치게 간섭할 우려가 있다고 생각했기 때문이다. 브런디지가 이러한 수익창출을 거부했다는 것은 IOC가 스폰서 계약이나 올림픽 상징의 사용에 대한 협상을 포기했다는 뜻이다. 브런디지가 IOC에 200만 달러를 남기고 은퇴한 후 8년 뒤에 IOC의 잔고는 4500만 달러로 늘어났다. 그 이유는 IOC가 처음으로 텔레비전 중계권을 판매하고 스폰서와 계약함으로써 올림픽의 팽창을 노리는 이데올로기(관념)의 변화가 있었기 때문이다. 1980년에 IOC위원장으로 후안 안토니오 사마란치가 당선되었을 때, 그의 소원이 IOC의 재정적 독립이었을 정도로 상업성에 대한 시각도 많이 달라졌다.  \n1984년 하계 올림픽은 올림픽 역사에 있어서 획기적인 순간이었다. 피터 워버로스(Peter Ueberroth)의 지휘하에 있던 LA 하계 올림픽 조직위원회는 그 당시 2억 2500만 달러라는 전례가 없던 이익을 얻었다. 왜냐하면 조직위원회는 독점스폰서에 대한 권리를 판매하였고 그로 인해 이익을 창출할 수 있었기 때문이다. IOC는 이러한 재정적 후원 권리를 통제하기 위한 방법을 강구했다. 1년 뒤인 1985년 사마란치 IOC 위원장은 올림픽 브랜드를 만들어내기 위한 '올림픽 프로그램(The Olympic Program, TOP)'을 설립했다. TOP의 회원들은 '독점'적이고, '비싼 비용'을 IOC에 지불해야만 한다. 4년마다 TOP 회원들은 5000만 달러를 내야 한다. 그 대가로 TOP의 회원은 생산하는 물품에 올림픽 상징인 오륜기를 국제적, 독점적으로 사용하고 출판물이나 광고에도 이용할 수 있는 혜택을 누리게 된다.",
  "국제 올림픽 위원회(이하 IOC로 지칭)는 몇몇 위원들이 한 행위에 대해서 비판을 받고 있다. 그 예로 IOC 위원장이었던 에이버리 브런디지와 후안 안토니오 사마란치가 대표적인 사람이다. 브런디지는 20년 넘게 IOC 위원장직을 맡았고 임기 중에 올림픽을 정치적으로 휘말려들지 않게 하기 위해 보호했다. 그러나 그는 남아프리카 공화국 대표단에게 아파르트헤이트와 관련된 이슈를 건드리고 반유대정책을 함으로써 비난을 받았다. 사마란치 위원장 시기 때는 족벌 정치와 부패로 비난받았다. 사마란치가 스페인에서 프랑코 정권에 협력했다는 것도 비판의 이유가 되었다.  \n1998년에 몇몇 IOC위원들이 2002년 솔트레이크 시티 동계 올림픽 유치 과정에서 미국에게 미국을 올림픽 개최지로 뽑아달라는 뇌물청탁을 받았다는 것이 폭로되었다. 이에 IOC는 사퇴한 IOC위원 4명과 강제 퇴출된 6명에 대한 조사를 했다. 이 스캔들은 이후에 개최지 선정에서 이와 같은 불미스러운 일이 일어나지 않게 하기 위해서 IOC가 개혁에 착수하도록 하는 긍정적인 역할을 하기도 했다.  \nBBC 다큐멘터리인 '파노라마'에서는 '매수된 올림픽'이란 주제로 2004년 8월에 방송을 내보내기도 했다. 이때 이 프로그램에서는 2012년 하계 올림픽의 개최지 선정과 관련된 뇌물에 대해서 조사했다. 이 다큐멘터리에서는 특정 후보 도시가 IOC 위원들에게 뇌물수수하는 것이 가능했다고 주장했으며, 특히 파리 시장이었던 베르트랑 들라노에(Bertrand Delanoë)는 영국의 총리인 토니 블레어와 런던올림픽유치위원회가 입후보 규정을 위반했다고 비난했다. 그는 당시 프랑스 대통령이었던 자크 시라크를 목격자로 내세웠지만 시라크 대통령은 이 분쟁에 휘말려드는 것을 주의했으며 인터뷰를 삼갔다. 결국 베르트랑 들라노에의 주장에 대한 조사는 체계적으로 이루어지지는 않았다. 2006년 동계 올림픽을 유치했던 토리노도 이 논쟁에서 빠져나갈 수 없었다. 이번에는 스위스 국적의 IOC위원 마크 호들러(Marc Hodler)가 이 논쟁의 중심이 되었는데, 이 위원은 스위스 시온의 경쟁 도시였던 토리노가 IOC위원들에게 뇌물수수를 했다고 말했고, 이 발언으로 광범위한 조사가 이루어졌다. 이 언행이 많은 IOC위원들이 시온에 대해 언짢게 생각하게 되고 토리노가 개최지로 선정되도록 도와주는 역할을 했을 가능성도 제기되고 있다.",
  '올림픽 브랜드의 판매는 항상 논란이 되어왔다. 비판 중 하나는 올림픽이 지나치게 상업성과 연계되어 이제 올림픽이 기존의 상업적인 스포츠쇼와 다를 게 없다는 것이다. 1996년과 2000년 하계 올림픽 기간 사이에는 올림픽 관련 상품 시장의 포화 상태가 일어나면서 IOC에게 또 다른 비판이 일었다. 개최도시가 올림픽 관련 물건들을 파려는 상인과 회사들로 넘쳐났던 것이다. IOC는 이에 대해 앞으로 다가올 올림픽에서는 과다 경쟁을 방지하고 이런 불미스라운 상황이 일어나지 않도록 대처하겠다고 응답했다. 또 다른 비판으로는, 개최국이나 개최도시는 올림픽에 모든 비용을 들이는데 IOC는 손도 까딱 않고 올림픽 상징으로부터 얻는 모든 권리와 수입을 독차지하고 있다는 점이다. IOC는 올림픽 상징으로 인한 수입 뿐 아니라 스폰서와 중계권에서 들어오는 수입의 일정 지분도 가져간다. 개최도시 입장에서는 그들의 투자가 흑자가 될지 확신하지도 못하는 상황에서 올림픽 개최도시로서의 권리를 위해 노력을 해야 한다.',
  '베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이지만 텔레비전으로 방송한 첫 번째 올림픽이었다. 1956년 동계 올림픽은 올림픽을 전 세계적으로 중계 방송한 첫 번째 올림픽이었으며, 1960년 동계 올림픽에서는 중계권을 어느 특정한 방송사에 판매한첫 번째 올림픽이다. 그 후 수십 년간 올림픽은 냉전중인 국가들의 이데올로기 선전의 장이 되었다. 강대국들은 정치 주권을 위해 IOC(국제 올림픽 위원회)를 조종했으며, IOC는 중계권 판매를 통해 이익을 높이고자 하였다. 중계권의 판매는 올림픽을 전 세계적으로 알리는 데 큰 기여를 했으며, 그로 인해 텔레비전의 광고 시간을 사는 광고주들에게 경쟁을 유발하여 IOC는 더욱더 많은 이익을 얻게 되었다. 이는 IOC에게 있는 중계권을 비롯한 수많은 권리들에 지불해야 할 금액들이 앞으로도 지속적으로 늘어나게 됨을 의미한다. 예를 들면 1998년 동계 올림픽 중계권을 사는 데 CBS는 3억 7500만 달러를 지불했지만 2000~2012년 올림픽의 중계권을 따내는 데 NBC는 35억 달러나 지불해야 했다.  \n올림픽 시청자들 또한 1960년대부터 기하급수적으로 증가했다. 1968년 하계 올림픽을 텔레비전으로 시청한 사람들은 6억 명으로 추측되었고, 1984년 하계 올림픽을 시청한 사람들은 9억 명으로 늘어났으며, 1992년 하계 올림픽은 약 35억 명이 시청한 것으로 추측되고 있다. 하지만 NBC의 조사에 의하면 시드니에서 열린 2000년 하계 올림픽은 1968년부터 개최된 올림픽 중에서 가장 적은 수의 사람들이 시청한 것으로 조사되었다. 시청자 수 감소의 원인으로 크게 두 가지가 지목되는데, 그중 하나는 케이블 채널 간의 경쟁이 심화된 것이고, 다른 하나는 실시간으로 경기 영상과 결과를 보여주는 인터넷의 대중화이다. 이러한 원인 분석에도 불구하고 텔레비전 방송국들은 아직도 지연방송에 의존하고 있다. 시청률 감소를 다르게 표현하자면 텔레비전 방송국에서는 광고 시간을 예전보다 싼 가격에 제공할 수밖에 없다는 것을 의미하기도 한다. 텔레비전 방송국들은 국제 올림픽 위원회에게 많은 방송 비용과 인터넷의 발달로 인한 케이블의 치열한 경쟁을 이유로 엄청난 중계권 가격을 조금 낮춰달라고 요구하고 있다. 결국 IOC는 올림픽 프로그램 진행 시간을 상당 부분 변경하게 된다. 예를 들면 하계 올림픽 때 체조종목은 밤 7시에서 9시까지 하는 것으로 바뀌었으며, 갈라쇼는 흥미를 높이는 데에 초점을 맞추게 되었다. 또한 IOC는 수영과 다이빙 종목의 시간은 늘렸는데, 이 종목은 텔레비전 시청자들 중 가장 인기가 있는 종목 중 하나이기 때문이다. 이는 미국 방송국들의 로비가 올림픽 종목들의 일정 시간까지도 미국의 텔레비전 황금시간대에 맞춰서 변경될 수 있음을 의미하는 것이었다. 이 변화는 장점과 단점이 혼재되어 있고, 그 예로 유럽에서 열렸던 2006년 동계 올림픽의 시청률은 미국 솔트레이크 시티에서 열렸던 2002년 동계 올림픽과 비교해보면 확연히 낮았으며 또한 베이징에서 열렸던 2008년 하계 올림픽의 시청자는 급격히 늘어났다.'],
 ["올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다.  \n#### 개막식  \n개막식 때는 올림픽 헌장에 따라 다양한 행사가 열린다. 개막식의 기본 토대는 벨기에 안트베르펜에서 열린 1920년 하계 올림픽 때 만들어졌다. 개막식은 대개 개최국의 국기가 게양되고 국가가 울려퍼지며 시작된다. 그 후에 개최국이 준비한 그들의 문화를 대표하는 음악, 춤, 영상 따위가 공연된다. 개막식은 아름답기가 매회가 지날수록 웅대해지고 복잡해지는데, 이는 전 대회보다 사람들의 기억에 오래도록 남기기 위함이다. 보도에 의하면 2008 베이징 올림픽 개막식 때 든 비용은 1억 달러로 그 대부분이 예술적인 부분에 들었다고 한다.  \n행사가 끝나면 다음에는 각국의 선수단이 입장한다. 올림픽의 발상지라는 영예를 가진 그리스가 전통적으로 맨 처음에 입장한다. 나머지 각국 선수단은 주최국에서 선택한 언어의 사전 순으로 입장하고 나서, 개최국 선수단이 제일 마지막에 입장한다. 그리스 아테네에서 열린 2004년 하계 올림픽에서는 그리스 국기가 맨 처음에 입장하고, 그리스 선수단이 맨 마지막에 입장했다. 개막식 마지막에는 올림픽 성화가 들어오고 마지막 성화 봉송자에게 전달할 때까지 돌게 된다. 마지막 성화 봉송자는 대체로 유명하고 올림픽에서 성공한 개최국의 선수가 하며 올림픽 성화를 경기장 내에 점화한다. 그 다음 올림픽조직위원장과 IOC 위원장이 개막 선언을 하는데 공식적으로 개막되었다는 것과 올림픽 성화가 점화되는 것을 선언한다. 그 다음에 올림픽조직위원장과 IOC 위원장이 개회사를 낭독하게 된다. 마자막으로 올림픽기 게양에 이어 올림픽 선서를 끝으로 개막식 과정은 모두 끝나게 된다. 2020년 하계 올림픽 이후로는 그리스 - 난민 올림픽 선수단 - 나머지 각국 선수단 - 차차기 올림픽 개최국 - 차기 올림픽 개최국 - 개최국 순서대로 입장한다.  \n#### 폐막식  \n폐막식은 올림픽 경기가 모두 끝난 후에 열린다. 각국의 기수가 경기장에 들어온 후에 국적에 상관없이 모든 선수들이 함께 들어온다. 3개의 기가 국가가 울려퍼지는 동안 게양되는데, 그 3개의 국기는 그리스의 국기(올림픽의 발상지임을 기념하기 위해), 개최도시의 국기, 다음 하계·동계 올림픽의 개최도시의 국기이다. 그 다음 올림픽조직위원장과 IOC 위원장이 폐막 선언을 하는데 공식적으로 폐막되었다는 것과 올림픽 성화가 꺼지는 것을 선언한다. 일명 '안트베르펜 세레모니'라고 하는 것도 진행되는데, 이는 올림픽 개최도시의 수장이 특별한 올림픽 기를 IOC 위원장에게 넘겨주면 그것을 또다시 다음 대회의 개최도시의 수장에게 넘겨주는 것으로서 1920 안트베르펜 올림픽 때부터 시작한 것으로 알려져 있다. 이 행사가 끝나면 짧게 다음 대회 개최지에 대한 소개로 홍보 영상이나 퍼포먼스가 진행된다.  \n#### 시상식  \n시상식은 각 종목이 끝날 때마다 열린다. 개인 혹은 팀으로 참가해서 1위를 하거나 2위 혹은 3위를 한 선수(들)은 시상대에 올라서서 존경의 뜻으로 메달을 수여받는다. 올림픽 위원들에게 메달을 받은 후에 1위를 한 선수의 국가가 울려퍼지고 1, 2, 3위를 한 선수들의 국기가 올라간다. 개최도시의 자원봉사자들도 시상식 때 활동하는데 메달을 준비하거나 꽃을 들고 이동하는 것과 같은 일을 한다. 올림픽 종목마다 시상식은 대체로 그 종목의 결승전(본선)이 끝난 후 거의 하루 뒤에 이루어진다. 남자 마라톤의 경우에는 시작은 올림픽 마지막 날 아침 일찍 하고 시상식은 그 날 저녁에 폐막식 도중에 이루어진다.",
  '고대 올림피아 경기를 제대로 구현한 최초의 시도는 혁명 시대의 프랑스에서 1796년부터 1798년까지 3년동안 실시했던 프랑스 국내 올림픽인 \'공화국 올림픽\'(L\'Olympiade de la République)이었다. 이 대회의 종목 중에는 고대 그리스 올림피아 경기 때 행한 일부 종목도 있었다. 특히 1798년 공화국 올림픽 대회는 미터법을 최초로 스포츠에 도입시킨 대회이기도 하다. 이후 52년뒤인 1850년에는 잉글랜드 슈롭셔주의 웬록에서 올림픽급의 대회가 열리기 시작하였다. 이 대회는 1859년에 아테네에서 열렸을 때 웬록 올림픽으로 명칭이 변경되었으며 지금도 열리고 있다. 브룩스 박사는 1859년에 아테네에서 열린 올림픽 경기의 내용을 이후 경기에 채택하였다. 1866년 런던의 수정궁에서는 윌리엄 페니 브룩스가 영국의 국가 올림픽 대회를 만들었다.  \n1821년 그리스에서는 오스만 제국의 지배에 반기를 들고 독립 전쟁이 일어나면서, 이때부터 올림픽 부활에 대한 관심이 생겨났다. 시인이자 신문 편집자였던 파나요티스 수초스(Παναγιώτης Σούτσος)는 1833년에 출간한 자신의 시 \'망자(亡者)의 대화\'에서 최초로 올림픽 부활에 대한 제안을 내놓았다. 그리스의 부유한 박애주의자였던 에방겔리스 자파스(Ευαγγέλης Ζάππας)는 1859년에 아테네 시 광장에서 열린 "올림픽 경기(일명 자파스 올림픽)"를 후원하였다. 이 경기에는 그리스와 오스만 제국 출신의 선수들이 참가하였다. 에방겔리스 자파스는 이후에도 올림픽 경기를 개최할 수 있도록 고대의 경기장이었던 파나티네코 경기장을 복원하는 데도 돈을 썼다. 파나티네코 경기장에서 1870년과 1875년에 자파스 올림픽을 개최했으며, 현대 올림픽인 2004년 하계 올림픽 때는 양궁 경기장으로도 쓰였다.  \n역사학자였던 쿠베르탱은 프로이센-프랑스 전쟁(1870–1871)에서 프랑스의 패배 원인을 분석하면서 군사들이 체계적인 체력 훈련을 받지 않았기 때문에 전쟁에서 패배했다고 말한 인물이다. 1890년 웬록 올림픽에 참석한 쿠베르탱은 그 이후부터 올림픽을 대규모로 부활시킬 수 있으리라 생각했다. 쿠베르탱은 웬록 올림픽과 자파스 올림픽을 토대로 하여 올림픽 경기를 국제적으로 시행하기 위해 나라별로 올림픽을 번갈아가며 개최하는 방식을 생각해냈다. 그는 이 방안을 새로 설립된 국제 올림픽 위원회(IOC)의 첫 올림픽 의회 기간 중에 언급했다. 총회는 파리의 소르본 대학교에서 1894년 6월 16일부터 6월 23일까지 7일간 지속되었으며, 총회 마지막날, 2년 후인 1896년에 아테네에서 국제적 규모의 올림픽 대회를 열기로 결정되었다. IOC는 올림픽을 조직하는 데에 모든 책임을 졌으며, 초대 위원장으로는 그리스의 작가였던 디미트리오스 비켈라스(Δημήτριος Βικέλας)가 선출되었다.',
  '고대의 올림픽 경기(올림피아 경기)는 고대 그리스의 여러 도시 국가의 대표선수들이 모여 벌인 일련의 시합이었으며, 육상 경기가 주 종목이지만 격투기와 전차 경기도 열렸다. 그리고 패배하면 죽기도 하였다. 고대 올림픽의 유래는 수수께끼로 남아있다. 잘 알려진 신화로는 헤라클레스와 그의 아버지인 제우스가 올림픽의 창시자였다는 것이다. 전설에 따르면 이 경기를 최초로 \'올림픽\'이라고 부르고, 4년마다 대회를 개최하는 관례를 만든 사람이 헤라클레스라고 한다. 어떤 전설에서는 헤라클레스가 이른바 헤라클레스의 12업을 달성한 뒤에 제우스를 기리고자 올림픽 경기장을 지었다고 한다. 경기장이 완성되자 헤라클레스는 일직선으로 200 걸음을 걸었으며, 이 거리를 "스타디온"이라 불렀는데, 후에 이것이 길이 단위인 \'스타디온\'(그리스어: στάδιον → 라틴어: 영어: stadium)이 되었다. 또 다른 설로는 \'올림픽 휴전\'(그리스어: ἐκεχειρία 에케케이리아[*])이라는 고대 그리스의 관념이 최초의 올림피아 경기와 관련이 있다고 한다. \'올림픽 휴전\'이란 어느 도시 국가라도 올림피아 경기 기간 중에 다른 나라를 침범하면 그에 대한 응징을 받을 수 있다는 뜻으로, "올림픽 기간에는 전쟁하지 말 것"으로 요약할 수 있다.  \n고대 올림피아 경기가 처음 열린 시점은 보통 기원전 776년으로 인정되고 있는데, 이 연대는 그리스 올림피아에서 발견된 비문에 근거를 둔 것이다. 이 비문의 내용은 달리기 경주 승자 목록이며 기원전 776년부터 4년 이후 올림피아 경기 마다의 기록이 남겨져 있다. 고대 올림픽의 종목으로는 육상, 5종 경기(원반던지기, 창던지기, 달리기, 레슬링, 멀리뛰기), 복싱, 레슬링, 승마 경기가 있었다. 전설에 따르면 엘리스의 코로이보스가 최초로 올림피아 경기에서 우승한 사람이라고 한다.  \n고대 올림피아 경기는 근본적으로 종교적인 중요성을 띄고 있었는데, 스포츠 경기를 할 때는 제우스(올림피아의 제우스 신전에는 페이디아스가 만든 제우스 상이 있음)와 펠롭스를 기리기 위하여 제물 봉헌 의식을 치렀다. 펠롭스는 올림피아의 전설상의 임금이었던 피사티스의 오이노마오스 왕과 전차 경주를 겨룬 영웅으로 유명한 인물이다. 올림피아 경기의 승자는 시와 조각상으로 칭송받았다. 올림피아 경기는 4년마다 열렸으며, 이 기간을 \'올림피아드\'(Olympiad)라고 했는데, 그리스인들은 이를 시간 단위로 이용하였다. 올림피아 경기는 고대 그리스에서 정기적으로 열렸던 범그리스 대회의 순환 대회 가운데 하나였다.  \n올림피아 경기는 기원전 6세기~기원전 5세기에 절정에 이르렀으나, 그 후 로마가 패권을 잡은 뒤 그리스에 영향력을 행사하면서 서서히 쇠퇴하게 된다. 고대 올림픽이 공식적으로 끝난 해는 확실히 알 수 없으나, 대부분 테오도시우스 1세 황제가 모든 이단 숭배 및 예배를 금지했던 393년을 고대 올림픽의 마지막이라고 추정한다. 다른 설에 따르면 테오도시우스의 후계자인 테오도시우스 2세가 모든 그리스 신전을 파괴하라고 명령한 426년이라고도 한다. 이렇게 올림픽이 사라진 이후로 이보다 한참 뒤인 19세기에 이르러서야 비로소 다시 올림픽 경기가 열리게 된다.',
  '1859년 자파스 올림픽에 참가한 선수의 수는 250명을 넘지 못했다. 에방겔리스 자파스는 "지난 자파스 올림픽을 포함, 1896년에 개최될 2번째 올림픽을 위해 파나티네코 경기장을 보수해야 한다."라는 충고를 하지만, 그리스 정부는 그의 말을 듣지 않았고 결국 1896년 아테네 올림픽 준비를 위해 파나티네코 경기장은 두 번이나 정비해야 했다. 1회 대회 정식종목으로는 9종목이 있었는데 육상, 사이클, 펜싱, 체조, 사격, 수영, 테니스, 역도, 레슬링이 있었으며, 조정도 정식종목이었으나 매우 나쁜 날씨로 인해 조정 경기는 취소되었다. 펜싱 경기는 역사적 건물인 자피온(에반젤리스 자파스의 이름을 딴 것이다)에서 열렸다. 그리스의 관리들과 국민들은 올림픽 경기 개최에 열광적이었다. 많은 선수들이 이에 동감하면서 앞으로도 올림픽 대회를 아테네에서 영구히 개최해야 한다고 요구하기까지 하였다. 그러나 국제올림픽위원회(IOC)는 근대 올림픽은 순환 개최로 열리는 세계적인 행사가 되어야 한다고 생각했다. 결국 2회 올림픽은 프랑스 파리에서 열기로 결정되었다.  \n#### 변화와 발전  \n1896년 올림픽 대회의 성공을 이어서 개최된 두 번째 올림픽인 1900년 올림픽에서는 올림픽의 존폐여부를 위협받는 지경에 이르게 되었다. 1900년에 파리와 1904년에 세인트루이스에서 열린 올림픽은 하필이면 엑스포와 시간과 장소가 겹치는 바람에 빛을 바래게 된다. 1904년 대회를 예로 들면 650명의 선수단이 참가했지만 그중 580명은 미국국적을 가진 사람이었다. 1900년과 1904년의 두 올림픽 대회는 역대 올림픽중에 최저점을 기록한다. 올림픽은 1906년 올림픽이 아테네에서 개최되었을 때 다시 일어서게 된다. 또 다른 성공적인 올림픽은 그리스 올림픽 협회가 조직했으며 세 차례나 올림픽을 치른 경기장에서 개최되었다. 이 경기는 비공식 올림픽이긴 했지만 세계적으로 상당한 참가자들을 불러 모았으며 대중들에게 큰 재미를 갖다주었다. 이 때를 시작으로 올림픽의 인기와 번영이 시작되었다.',
  '올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.'],
 ["올림픽 경기 종목은 총 33개부문 52개 종목에서 약 400개의 경기로 이루어져있다. 예를 들어서 하계 올림픽 부문인 레슬링은 자유형과 그레코로만형의 두 종목으로 나뉜다. 여기에서 10경기는 남자부, 4경기는 여자부로 열리며 분류기준은 체중이다. 하계 올림픽은 26개, 동계 올림픽은 7개 부문으로 이루어져있다. 하계 올림픽에서는 육상, 수영, 펜싱, 체조가 1회 대회때부터 한번도 빠짐없이 정식종목이었으며, 동계 올림픽에서는 크로스컨트리, 피겨 스케이팅, 아이스 하키, 노르딕 복합, 스키 점프, 스피드 스케이팅이 1924년 동계 올림픽부터 빠짐없이 정식종목이었다. 배드민턴, 농구, 배구와 같은 정식종목들은 처음에는 시범종목이었으며 그 후에 정식종목으로 승인 되었다. 야구처럼 예전에는 정식종목 이었지만 지금은 정식 종목에서 빠진 종목도 있다.  \n각 올림픽 종목들은 IOC로부터 승인을 받은 국제경기연맹의 관리를 받는다. 35개의 연맹이 IOC에서 승인을 받았으며, 승인을 받았지만 현재 정식종목이 아닌 종목을 감독하는 연맹도 있다. IOC의 승인을 받았지만 올림픽 종목이 아닌 스포츠들은 올림픽 종목으로 고려되지는 않으나, 올림픽이 끝난 후 처음으로 열리는 IOC총회 때마다 정식종목이 되도록 신청을 할 수는 있다. IOC 총회 때 정식종목 선정은 총회에 참석중인 IOC위원들의 투표를 통해 이루어지며, 재적 위원 수의 과반수 이상 찬성표를 얻어야 정식종목으로 인정을 받는다. IOC의 승인을 받은 스포츠이나 찬성표를 받지 못해 정식종목이 되지 못한 스포츠로는 체스와 서핑과 같은 것이 있다.  \n2004년 10월과 11월에 IOC는 '올림픽 프로그램 위원회'(Olympic Programme Commission)를 설립했다. 여기서는 올림픽 종목과 올림픽 종목이 아닌 스포츠를 모두 재검토하는 일을 한다. 이 위원회의 목표는 올림픽 종목에 더 체계적으로 다가가는 것이다. 위원회에서는 우선적으로 올림픽 종목으로 포함되기 위해서는 7개의 기준을 충족시켜야 한다고 말한다. 이 7개의 기준은 역사, 전통, 보편성, 인기도와 잠재성, 선수의 건강, 연맹의 스포츠를 관리할만한 능력, 스포츠를 여는 데에 필요한 비용이다. 예를 들면 2012년 하계 올림픽의 정식종목 후보에 7개 조건을 포함한 비(非)올림픽 스포츠가 올랐고 그 내용은, 골프, 가라테, 럭비, 인라인 스케이팅, 스쿼시였다. 이 스포츠들은 IOC 상임이사회에서 재검토되어 2005년 7월에 열린 싱가포르 총회에서 최종 결정하기로 했다. 결국 5개 중 2개(가라테와 스쿼시) 가 최종 후보로 올라왔으나 가라테와 스쿼시 둘 다 2/3의 미만의 찬성표로 정식종목이 되지는 못한다. 그 후 2016년 올림픽 정식종목에는 7개의 스포츠가 정식종목 신청을 했는데, 내용은 가라테, 골프, 스쿼시, 야구, 소프트볼, 7인제 럭비, 인라인 스케이팅이었다. 2009년 8월 13일, 신청된 7개의 스포츠 중 단 2개만 최종후보로 선정되었는데, 이는 7인제 럭비와 골프였다. 같은해인 2009년 10월에 열린 IOC 총회에서 골프와 럭비는 과반수 이상의 득표를 얻어서 2016년 하계 올림픽과 2020년 하계 올림픽의 정식종목으로 채택되었다.  \n2002년에 열린 제114차 IOC 총회에서는 하계 올림픽 종목은 최대 28부문 301개 경기에 10,500명이 참가하는 것으로 제한하기로 결정했다. 그 후 3년 뒤인 제117차 IOC 총회에서는 정식종목이었던 야구와 소프트볼을 정식 종목에서 제외시킨다. 이 결과에 대한 이견이 없었으므로 2012년 올림픽 때는 26개부문에서 경기가 열린다. 2016년과 2020년 올림픽 때는 럭비와 골프가 추가되어 다시 28개부문에서 경기가 열린다.",
  '올림픽(영어: Olympic Games, 프랑스어: Jeux olympiques)은 전 세계 각 대륙 각국에서 모인 수천 명의 선수가 참가해 여름과 겨울에 스포츠 경기를 하는 국제적인 대회이다. 전 세계에서 가장 큰 지구촌 최대의 스포츠 축제인 올림픽은 세계에서 가장 인지도있는 국제 행사이다. 올림픽은 2년마다 하계 올림픽과 동계 올림픽이 번갈아 열리며, 국제 올림픽 위원회(IOC)가 감독하고 있다. 또한 오늘날의 올림픽은 기원전 8세기부터 서기 5세기에 이르기까지 고대 그리스 올림피아에서 열렸던 올림피아 제전에서 비롯되었다. 그리고 19세기 말에 피에르 드 쿠베르탱 남작이 고대 올림피아 제전에서 영감을 얻어, 근대 올림픽을 부활시켰다. 이를 위해 쿠베르탱 남작은 1894년에 IOC를 창설했으며, 2년 뒤인 1896년에 그리스 아테네에서 제 1회 올림픽이 열렸다. 이때부터 IOC는 올림픽 운동의 감독 기구가 되었으며, 조직과 활동은 올림픽 헌장을 따른다. 오늘날 전 세계 대부분의 국가에서 올림픽 메달은 매우 큰 영예이며, 특히 올림픽 금메달리스트는 국가 영웅급의 대우를 받으며 스포츠 스타가 된다. 국가별로 올림픽 메달리스트들에게 지급하는 포상금도 크다. 대부분의 인기있는 종목들이나 일상에서 쉽게 접하고 즐길 수 있는 생활스포츠 종목들이 올림픽이라는 한 대회에서 동시에 열리고, 전 세계 대부분의 국가 출신의 선수들이 참여하는 만큼 전 세계 스포츠 팬들이 가장 많이 시청하는 이벤트이다. 2008 베이징 올림픽의 모든 종목 누적 시청자 수만 47억 명에 달하며, 이는 인류 역사상 가장 많은 수의 인구가 시청한 이벤트였다.  \n또한 20세기에 올림픽 운동이 발전함에 따라, IOC는 변화하는 세계의 사회 환경에 적응해야 했다. 이러한 변화의 예로는 얼음과 눈을 이용한 경기 종목을 다루는 동계 올림픽, 장애인이 참여하는 패럴림픽, 스페셜 올림픽, 데플림픽, 10대 선수들이 참여하는 유스 올림픽 등을 들 수 있다. 그 뿐만 아니라 IOC는 20세기의 변화하는 경제, 정치, 기술 환경에도 적응해야 했다. 그리하여 올림픽은 피에르 드 쿠베르탱이 기대했던 순수한 아마추어 정신에서 벗어나서, 프로 선수도 참가할 수 있게 되었다. 올림픽은 점차 대중 매체의 중요성이 커짐에 따라 올림픽의 상업화와 기업 후원을 놓고도 논란이 생겨났다. 또한 올림픽을 치르며 발생한 보이콧, 도핑, 심판 매수, 테러와 같은 수많은 일들은 올림픽이 더욱 굳건히 성장할 수 있는 원동력이 되었다.  \n올림픽은 국제경기연맹(IF), 국가 올림픽 위원회(NOC), 각 올림픽의 위원회(예-벤쿠버동계올림픽조직위원회)로 구성된다. 의사 결정 기구인 IOC는 올림픽 개최 도시를 선정하며, 각 올림픽 대회마다 열리는 올림픽 종목도 IOC에서 결정한다. 올림픽 경기 개최 도시는 경기 축하 의식이 올림픽 헌장에 부합하도록 조직하고 기금을 마련해야 한다. 올림픽 축하 행사로는 여러 의식과 상징을 들 수 있는데 올림픽기나 성화가 그 예이다.  \n올림픽은 거의 모든 국가가 참여할 정도로 규모가 커졌다. 하계 올림픽은 33개의 종목과 약 400개의 세부종목에서 13,000명이 넘는 선수들이 겨루고 그중 각 종목별 1, 2, 3위는 각각 금/은/동을 수여받는다. 전 세계 언론에서 각각 4년마다 열리는 올림픽 경기를 중계하기 때문에 이름 없는 선수가 개인적, 국가적, 세계적으로 명성을 얻을 수 있는 기회가 된다. 이와 더불어 올림픽 경기는 개최지와 개최국에게도 전 세계에 그 이름을 널리 알리는 좋은 기회가 된다.',
  '동계 올림픽은 눈과 얼음을 이용하는 스포츠들을 모아 이루어졌으며 하계 올림픽 때 실행하기 불가능한 종목들로 구성되어 있다. 피겨스케이팅, 아이스하키는 각각 1908년과 1920년에 하계올림픽 종목으로 들어가 있었다. IOC는 다른 동계 스포츠로 구성된 새로운 대회를 만들고 싶어 했고, 로잔에서 열린 1921년 올림픽 의회에서 겨울판 올림픽을 열기로 합의했다. 1회 동계올림픽은 1924년, 프랑스의 샤모니에서 11일간 진행되었고, 16개 종목의 경기가 치러졌다. IOC는 동계 올림픽이 4년 주기로 하계 올림픽과 같은 년도에 열리도록 했다. 이 전통은 프랑스의 알베르빌에서 열린 1992년 올림픽 때까지 지속되었으나, 노르웨이의 릴레함메르에서 열린 1994년 올림픽부터 동계 올림픽은 하계 올림픽이 끝난지 2년후에 개최하였다.',
  '올림픽 활동이란 많은 수의 국가, 국제 경기 연맹과 협회 • 미디어 파트너를 맺기 • 선수, 직원, 심판, 모든 사람과 기관이 올림픽 헌장을 지키는 것을 말한다.국제올림픽위원회(IOC)는 모든 올림픽 활동을 통솔하는 단체로서, 올림픽 개최 도시 선정, 계획 감독, 종목 변경, 스폰서 및 방송권 계약 체결 등의 권리가 있다. 올림픽 활동은 크게 세 가지로 구성된다.  \n- 국제경기연맹(IF)은 국제적인 규모의 경기를 관리, 감독하는 기구이다. 예를 들어서 국제 축구 연맹(FIFA)는 축구를 주관하며, 국제 배구 연맹(FIVB)은 배구를 주관하는 기구이다. 올림픽에는 현재 35개의 국제경기연맹이 있고 각 종목을 대표한다. (이 중에는 올림픽 종목은 아니지만 IOC의 승인을 받은 연맹도 있다.)\n- 국가 올림픽 위원회(NOC)는 각국의 올림픽 활동을 감독하는 기구이다. 예를 들어서 대한 올림픽 위원회(KOC)는 대한민국의 국가 올림픽 위원회이다. 현재 IOC에 소속된 국가 올림픽 위원회는 205개이다.\n- 올림픽 조직 위원회(OCOG)는 임시적인 조직으로 올림픽의 총체적인 것(개막식, 페막식 등)을 책임지기 위해 구성된 조직이다. 올림픽 조직 위원회는 올림픽이 끝나면 해산되며 최종보고서를 IOC에 제출한다.  \n올림픽의 공식언어는 프랑스어와 영어와 개최국의 공용어이다. 모든 선언(예를 들어서 개막식 때 각국 소개를 할 때)들은 세 언어가 모두 나오거나 영어나 프랑스어 중에서 한 언어로만 말하기도 한다. 개최국의 공용어가 영어나 프랑스어가 아닐 때는 당연히 그 나라의 공용어도 함께 나온다.',
  '올림픽 개최지는 해당 올림픽 개최 7년 전에 IOC 위원들의 투표로 결정된다. 개최지 선정에는 약 2년이 걸린다. 유치를 희망하는 도시는 우선 자국의 올림픽 위원회에 신청을 해야 한다. 만약 한 국가에서 두 도시 이상이 유치를 희망한다면, 한 국가당 한 도시만 후보가 될 수 있다는 규칙에 따라 내부적으로 후보 도시를 결정해야 한다. 후보 도시가 결정되면 후보 도시가 소속된 국가의 올림픽 위원회는 IOC에 개최 신청을 하고, 신청 후에는 올림픽 개최에 대한 질의 응답서를 보내야 한다. 이 질의응답서에서 신청한 도시는 올림픽 헌장을 준수하며 IOC 상임이사회에 의한 다른 규정들을 지킬 것이라는 확신을 주어야 한다. 이 질의응답서는 전문가들이 검토하여 신청 도시들의 잠재성과 계획을 평가한다. 이 전문적인 평가를 바탕으로 IOC 상임이사회에서는 신청도시 중에서 후보도시를 고른다.  \n후보도시로 선택되면 그 도시들은 IOC에 보내는 후보도시에 관한 문서에 그들의 계획을 더욱 상세하고 방대한 양으로 적어서 보내야 한다. 평가조사단들이 이 후보도시들을 평가한다. 평가조사단은 후보도시들을 방문해서 지역 관계자들과 회견을 갖고 경기장 시설을 세심하게 조사한 뒤 개최지 투표를 하기 한달전에 조사를 바탕으로 한 공식 보고를 한다. 회견을 하는 동안에도 후보도시들은 자신들이 올림픽을 개최하는 데 충분한 자금이 조달될 수 있는지 등을 입증할 수 있어야 한다. 평가조사단의 업무가 끝나면 후보지의 국가 위원들은 IOC 정기총회에 참석한다. 이 총회에서 IOC 위원들은 올림픽 개최지를 선정하게 되며 후보지의 국가에 소속된 위원들은 자국의 후보지가 탈락하지 않는 이상 투표를 할 수 없다. 투표가 끝난후에 개최지로 선정된 곳의 유치위원회가 IOC와 개최도시 계약서에 서명을 하면 공식적으로 올림픽 개최도시(개최국)으로 인정된다.  \n2016년까지 올림픽은 23개국 44개 도시에서 열렸으며 유럽과 북아메리카대륙 이외의 대륙에서는 고작 8번 밖에 개최하지 못했다. 1988년 하계 올림픽이 대한민국의 서울에서 열린것을 시작으로 그 후 아시아와 오세아니아 대륙에서 올림픽이 4번이나 열렸으며, 이는 그 이전의 현대 올림픽사와 비교해보면 엄청나게 늘어난 수치였다. 2016년 하계 올림픽이 개최된 브라질의 리우데자네이루는 남미에서 열리는 첫 번째 올림픽이다. 아직 아프리카에서는 올림픽이 한 번도 개최되지 않았다. 2008년 하계 올림픽 때 가장 많은 선수가 참여한 나라는 중국으로 639명이 참가했으며 그 다음은 미국과 러시아로 각각 596명과 455명이 참가했다.  \n미국은 5번의 하계 올림픽과 4번의 동계 올림픽을 개최하면서 최다 올림픽을 개최한 나라이다. 영국은 2012년에 3번째 올림픽을 개최하였다. 독일, 오스트레일리아, 그리스는 하계 올림픽을 2번 개최한 국가이다. 동계 올림픽에서는 이탈리아가 2026년 밀라노-코르티나담페초 개최지로 선정되어 3번 개최될 예정이다. 또한 프랑스가 3번을 개최했으며 2024년 하계올림픽 개최예정으로 영국에 이번 두 번째로 한 도시에서 3번 올림픽 개최하며 하계올림픽3번 개최하였다. 프랑스는 동계, 하계 올림픽 각 3번씩 총 6번 개최로 9번으로 최다개최국인 미국 다음으로 두 번째로 많이 개최한 국가가 된다. 스위스, 오스트리아, 노르웨이, 일본, 이탈리아는 2번씩 개최했다. 일본은 하계,동계 각 2번씩 총 4번으로 미국, 프랑스 다음 세번째로 많이 개최한 국가이다. 2010년에 밴쿠버에서 열린 2010년 동계 올림픽은 캐나다에서 열리는 두 번째 동계 올림픽이고, 동/하계 올림픽을 합쳐 캐나다에서 3번째로 개최되는 올림픽이다.'],
 ['올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.',

In [45]:
###################################################
# eval_df에 컬럼으로 추가
###################################################
eval_df['response'] = response_list
eval_df['retrieved_contexts'] = retrieved_context_list
eval_df.head()

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name,response,retrieved_context,retrieved_contexts
0,후안 안토니오 사마란치가 IOC 위원장으로 당선된 후 올림픽 상업성에 어떤 변화가 ...,[1950년대까지 IOC는 적은 예산으로 운영되어 왔다. 에이버리 브런디지가 위원장...,"1980년에 IOC위원장으로 후안 안토니오 사마란치가 당선되었을 때, 그의 소원이 ...",Sports Business Analyst,MISSPELLED,MEDIUM,single_hop_specific_query_synthesizer,"후안 안토니오 사마란치가 IOC 위원장으로 당선된 뒤, 올림픽은 **상업성을 받아들...",[처음에 IOC는 스폰서에게서 자금제공을 받는 것을 거부했었다. 이런 방침은 에이버...,[처음에 IOC는 스폰서에게서 자금제공을 받는 것을 거부했었다. 이런 방침은 에이버...
1,아테네 올림픽 개막식에서 그리스 선수단의 입장 순서는 어떻게 되었나요?,"[올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다. \n#...",그리스 아테네에서 열린 2004년 하계 올림픽에서는 그리스 국기가 맨 처음에 입장하...,Olympics Enthusiast,MISSPELLED,MEDIUM,single_hop_specific_query_synthesizer,정보가 부족해 답을 할 수없습니다.,"[올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다. \n#...","[올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다. \n#..."
2,"동계 올림픽 뭐뭐 있나, 몇 개 부문 있고 언제부터 어떤 종목 계속 있었는지, 그리...",[올림픽 경기 종목은 총 33개부문 52개 종목에서 약 400개의 경기로 이루어져있...,"동계 올림픽은 7개 부문으로 이루어져 있고, 크로스컨트리, 피겨 스케이팅, 아이스 ...",Olympics Enthusiast,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer,동계 올림픽에 대한 내용은 context에 다음과 같이 있습니다.\n\n- **동계...,[올림픽 경기 종목은 총 33개부문 52개 종목에서 약 400개의 경기로 이루어져있...,[올림픽 경기 종목은 총 33개부문 52개 종목에서 약 400개의 경기로 이루어져있...
3,"올림픽 성화와 그리스의 관계는 무엇이며, 성화가 어떻게 채화되는지 설명해 주세요.",[올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용...,매 올림픽이 시작되기 몇 개월 전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아...,Sports Business Analyst,PERFECT_GRAMMAR,LONG,single_hop_specific_query_synthesizer,"올림픽 성화는 **매 올림픽이 시작되기 몇 개월 전, 고대 그리스의 올림피아에서 채...",[올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용...,[올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용...
4,"1948년 런던 올림픽 그때 뭐 있었고 왜 중요한지 설명해줘, 잘 모르겠는데 그때 ...",[패럴림픽(Paralympic)은 신체·감각 장애가 있는운동 선수가 참가하는 국제 ...,1948년에 루드비히 구트만 경은 제2차 세계대전에 참전한 군인들의 사회 복귀를 위...,Olympic Sports Program Coordinator,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer,정보가 부족해 답을 할 수없습니다.,"[쿠베르탱의 생각과는 달리, 올림픽이 세계에 완벽한 평화를 가져다주지는 못했다. 실...","[쿠베르탱의 생각과는 달리, 올림픽이 세계에 완벽한 평화를 가져다주지는 못했다. 실..."

In [46]:
# eval_df를 RAGAS의 평가 데이터셋 타입으로 변환.
from ragas import EvaluationDataset
eval_dataset = EvaluationDataset.from_pandas(
    eval_df[["user_input", "retrieved_contexts", "response", "reference"]]
)
eval_dataset

EvaluationDataset(features=['user_input', 'retrieved_contexts', 'response', 'reference'], len=10)

In [48]:
#############################
# 평가
#############################
from ragas.metrics import (
    LLMContextRecall, # Context Recall
    LLMContextPrecisionWithReference, # Context Precision
    Faithfulness,
    AnswerRelevancy
)
from ragas import evaluate

C:\Users\Playdata\AppData\Local\Temp\ipykernel_23384\1150867979.py:4: DeprecationWarning: Importing LLMContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextRecall
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_23384\1150867979.py:4: DeprecationWarning: Importing LLMContextPrecisionWithReference from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextPrecisionWithReference
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_23384\1150867979.py:4: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_23384\1150867979.py:4: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import (

In [51]:
# 평가할 때 사용할 LLM, Embedding 모델
eval_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
eval_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

# Metric(평가지표) 객체를 List로 묶어준다.
## 내가 평가할 지표들만 묶어준다.
metrics = [
    LLMContextRecall(llm=eval_llm),
    LLMContextPrecisionWithReference(llm=eval_llm),
    Faithfulness(llm=eval_llm),
    AnswerRelevancy(llm=eval_llm, embeddings= eval_embeddings)
]
# 평가진행
eval_result = evaluate(dataset=eval_dataset, metrics=metrics)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_23384\4169728312.py:2: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  eval_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
C:\Users\Playdata\AppData\Local\Temp\ipykernel_23384\4169728312.py:3: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  eval_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

Evaluating:   0%|          | 0/40 [00:00<?, ?it/s]

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Task was destroyed but it is pending!
task: <Task pending name='Task-3451' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3452' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
c:\SKN31_\SKN31\.venv\Lib\site-packages\h11\_connection.py:275: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  old_states = dict(self._cstate.states)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-3452' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3470' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3471' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3471' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Task was destroyed but it is pending!
task: <Task pending name='Task-3480' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3481' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
Exception ignored in: <coroutine object Kernel.shell_main at 0x000001F3B3B68940>
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
KeyError: '__import__'
Exception ignored in: <coroutine object Kernel.shell_main at 0x000001F3B3B68940>
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
KeyError: '__import__'
Task was destroyed but it is pending!
task: <Task pending name='Task-3481' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3485' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3486' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
Exception ignored in: <coroutine object Kernel.shell_main at 0x000001F3B3B6AE40>
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
KeyError: '__import__'
Task was destroyed but it is pending!
task: <Task pending name='Task-3486' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Task was destroyed but it is pending!
task: <Task pending name='Task-3517' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3518' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
c:\SKN31_\SKN31\.venv\Lib\site-packages\urllib3\connection.py:412: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  if not any(isinstance(v, str) and v == SKIP_HEADER for v in values):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-3518' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Exception raised in Job[2]: TimeoutError()
Exception raised in Job[6]: TimeoutError()
Exception raised in Job[10]: TimeoutError()
Exception raised in Job[14]: TimeoutError()
Task was destroyed but it is pending!
task: <Task pending name='Task-3537' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3538' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\base_events.py:146: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  socket.inet_pton(af, host)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-3538' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Task was destroyed but it is pending!
task: <Task pending name='Task-3561' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3562' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\copy.py:253: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  args = (deepcopy(arg, memo) for arg in args)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-3562' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3564' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3565' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3565' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3570' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3571' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3571' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Exception raised in Job[16]: TimeoutError()
Exception raised in Job[18]: TimeoutError()
Exception raised in Job[20]: TimeoutError()
Exception raised in Job[22]: TimeoutError()
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001F36A7BE800> is already entered
Task was destroyed but it is pending!
task: <Task pending name='Task-3585' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3586' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
C:\Users\Playdata\AppData\Roaming\uv\python\cpython-3.13-windows-x86_64-none\Lib\contextlib.py:136: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def __enter__(self):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-3586' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3593' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3594' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3594' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3596' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3597' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3597' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3599' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3600' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3600' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3602' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3603' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3603' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3608' coro=<_async_in_context.<locals>.run_in_context() done, defined at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-3609' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at c:\SKN31_\SKN31\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3609' coro=<Kernel.shell_main() running at c:\SKN31_\SKN31\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Exception raised in Job[24]: TimeoutError()
Exception raised in Job[26]: TimeoutError()

In [52]:
eval_result

{'context_recall': 1.0000, 'llm_context_precision_with_reference': 0.8333, 'faithfulness': 0.6667, 'answer_relevancy': 0.4421}

In [ ]:
# print(type(eval_result))
## 개별 평가데이터에 대한 평가점수.
result_df = eval_result.to_pandas()

In [54]:
result_df

,user_input,retrieved_contexts,response,reference,context_recall,llm_context_precision_with_reference,faithfulness,answer_relevancy
0,후안 안토니오 사마란치가 IOC 위원장으로 당선된 후 올림픽 상업성에 어떤 변화가 ...,[처음에 IOC는 스폰서에게서 자금제공을 받는 것을 거부했었다. 이런 방침은 에이버...,"후안 안토니오 사마란치가 IOC 위원장으로 당선된 뒤, 올림픽은 **상업성을 받아들...","1980년에 IOC위원장으로 후안 안토니오 사마란치가 당선되었을 때, 그의 소원이 ...",1.0,1.000000,NaN,0.925351
1,아테네 올림픽 개막식에서 그리스 선수단의 입장 순서는 어떻게 되었나요?,"[올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다. \n#...",정보가 부족해 답을 할 수없습니다.,그리스 아테네에서 열린 2004년 하계 올림픽에서는 그리스 국기가 맨 처음에 입장하...,1.0,1.000000,NaN,0.000000
2,"동계 올림픽 뭐뭐 있나, 몇 개 부문 있고 언제부터 어떤 종목 계속 있었는지, 그리...",[올림픽 경기 종목은 총 33개부문 52개 종목에서 약 400개의 경기로 이루어져있...,동계 올림픽에 대한 내용은 context에 다음과 같이 있습니다.\n\n- **동계...,"동계 올림픽은 7개 부문으로 이루어져 있고, 크로스컨트리, 피겨 스케이팅, 아이스 ...",1.0,1.000000,NaN,0.665328
3,"올림픽 성화와 그리스의 관계는 무엇이며, 성화가 어떻게 채화되는지 설명해 주세요.",[올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용...,"올림픽 성화는 **매 올림픽이 시작되기 몇 개월 전, 고대 그리스의 올림피아에서 채...",매 올림픽이 시작되기 몇 개월 전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아...,1.0,1.000000,NaN,0.678446
4,"1948년 런던 올림픽 그때 뭐 있었고 왜 중요한지 설명해줘, 잘 모르겠는데 그때 ...","[쿠베르탱의 생각과는 달리, 올림픽이 세계에 완벽한 평화를 가져다주지는 못했다. 실...",정보가 부족해 답을 할 수없습니다.,1948년에 루드비히 구트만 경은 제2차 세계대전에 참전한 군인들의 사회 복귀를 위...,NaN,0.000000,NaN,0.000000
5,"올림픽 상징인 오륜기가 상업적으로 어떻게 활용되었으며, 오륜기의 의미는 무엇인가?",[올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용...,오륜기는 상업적으로는 IOC가 **올림픽 브랜드와 함께 독점적으로 사용·판매되는 상...,올림픽 상징인 오륜기는 1985년 IOC가 설립한 올림픽 프로그램(TOP)을 통해 ...,NaN,0.500000,NaN,0.531642
6,1920년 하계 올림픽 개막식이랑 폐막식에서 시작된 전통은 뭐에요?,"[올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다. \n#...",정보가 부족해 답을 할 수없습니다.,"1920년 하계 올림픽 개막식에서는 개막식의 기본 토대가 만들어졌고, 폐막식에서는 ...",NaN,1.000000,NaN,0.000000
7,"1984년 하계 올림픽이 올림픽의 상업화와 재정 구조에 어떤 변화를 가져왔으며, 이...",[1950년대까지 IOC는 적은 예산으로 운영되어 왔다. 에이버리 브런디지가 위원장...,1984년 하계 올림픽은 올림픽의 **상업화와 재정 구조가 크게 바뀐 획기적인 전환...,1984년 하계 올림픽은 LA 하계 올림픽 조직위원회가 독점스폰서 권리를 판매하여 ...,1.0,0.833333,1.0,0.900933
8,1960년 하계 올림픽과 관련하여 패럴림픽의 시작과 그 이후 올림픽 개최 도시와의 ...,[패럴림픽(Paralympic)은 신체·감각 장애가 있는운동 선수가 참가하는 국제 ...,"1960년 로마에서 열린 하계 올림픽 때, 루드비히 구트만이 400명의 선수들을 “...",패럴림픽은 1960년 로마에서 열린 하계 올림픽 때 루드비히 구트만이 400명의 선...,1.0,1.000000,1.0,0.719570
9,"올림픽 개막식과 폐막식에서 그리스가 어떤 특별한 역할을 하며, 이러한 전통이 올림픽...","[올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다. \n#...",정보가 부족해 답을 할 수없습니다.,올림픽 개막식에서는 올림픽의 발상지라는 영예를 가진 그리스가 전통적으로 맨 처음에 ...,1.0,1.000000,0.0,0.000000